### ISSUE TITLE
 TSS/CAGE within_peak: FALSE dist_peak: 50

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#113]
Good afternoon,
I have a question related to TSS/CAGE peak info. I dont understand conceptually how the start site can be "within_peak: FALSE" but the "dist_peak: 50". if it is 50bp distant of the peak it shouldn't it be classified true within_peak?
Thank you
Beatriz

**Comment by aarzalluz** [comment]
Hi @BeatrizdeToledo,

The dist_peak value is computed relative to the center of the peak, therefore, it is likely that, in those cases, the nearest CAGE peak is narrower than 50bp. Of course, you can always visualize your CAGE data and transcripts using GenomeBrowser to verify this. I will close the issue for now, but please let us know if you run any further tests and obtain results that may indicate otherwise.

Best,

Ángeles

**Comment by kullrich** [comment]
Dear @aarzalluz,

we are running into a similar situation with our data and not sure, why the within_peak is False.

We have altered the find function to see why and it turned out that it is due to the following lines:

```
 # Skip those cage peaks that are downstream the detected TSS because degradation just make the transcript shorter
            if strand=='+' and start0>int(query) and end1>int(query):
                continue
            if strand=='-' and start0<int(query) and end1<int(query):
                continue
```

Could you please indicate and clarify the skipping reason, maybe providing a citation to understand the reason behind it?

Thank you in anticipation

Best regards

Kristian

**Comment by FJPardoPalacios** [comment]
Hi @kullrich ,

I wrote a comment in the code you copied to explain why we don't want to associate a certain TSS to a peak that is downstream.
CAGE peaks are evidence of Transcription Starting Sites and degradation will not make an isoform longer (obviously), so it wouldn't have a lot of sense to say that a peak that is located in the body of the isoform is supporting a TSS which is upstream, no matter how close it is (as long as it is outside of the CAGE peak). I don't have any citation for that, but I think it's more common sense than anything else.

Regarding the cases of isoforms with `within_CAGE_peak == TRUE` and a low value for `dist_to_CAGE_peak`, as Angeles mentioned, SQANTI3 calculates the distance between the TSS and the center of the CAGE peak. Some peaks are as narrow as 20bp, so even if the TSS is only 30bp downstream the middle point of the CAGE peak, **it will not be within the peak**, it will be outside.

Hope this was helpful,

Bests,
Fran
