### ISSUE TITLE
ORF prediction

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#120]
Hi, 
there are usually 6 results in the the ORF prediction, so I wanted to ask how the SQANTI3 knows which is the right one to present in the report? Thanks

**Comment by FJPardoPalacios** [comment]
Hi,
SQANTI3 runs GeneMarkS-T with `--strand direct` option, since SQANTI3 expects that the transcripts models in FASTA format are already oriented. That leaves the ORF prediction possibilities to 3. And besides that, it's not a SQ3 decision, it's taken by GeneMarkS-T. I read in [their paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4499116/) that they calculate the odds to know what is the most likely ORF. I would bet that those odds are based mainly on the length of the resulting CDS and the starting and ending codon (if any).

Fran
