### ISSUE TITLE
Possible Problem in reference splice donors and acceptors parsing

### ISSUE THREAD

**Issue by lzx325** [ConesaLab/SQANTI3#123]
I think there is a problem when parsing the reference splice donors and acceptors here using the genePred file.

https://github.com/ConesaLab/SQANTI3/blob/ee51733c54e7e79630bf681771115f19ceb00847/sqanti3_qc.py#L664-L679

In L673, `d` is always on the 5' side, and `a` is always on the 3' side. `d` is a donor, and `a` is an acceptor only when the strand is positive.
Also, `junctions_by_chr` stores the locations of donors and acceptors on both the positive strand and the negative strand, without distinguishing them. If, for example, a negative-strand query junction only matches some reference junctions on the positive strand, should we treat the query as NIC or NNC?

**Comment by FJPardoPalacios** [comment]
Well, I think we will treat them as an **Antisense** since they are located in the opposite strand while it overlaps a known gene. You are right about the misleading naming of `donors` and `acceptors` (which is only kept in the guts of the code, I think SQ3 do not report the donor or acceptor status of the splice sites), but I would say that's not problem because of this:
 
https://github.com/ConesaLab/SQANTI3/blob/ee51733c54e7e79630bf681771115f19ceb00847/sqanti3_qc.py#L980-L995

The first thing we do when evaluating one match between an input transcript and a reference gene is to check the strand (L992). If they are in opposite strands, we take note of the reference gene and keep looking at the rest of the matching genes. So we only look at the splice sites if both the input and the reference are in the same strand. In that case, it doesn't matter if we call them donors or acceptors because we know they are oriented the same way. `donnors` will be always the lowest coordinate in the pair and `acceptors` the highest, regardless their strand.

Hope this answer helps you. If you have any doubt, let me know. Otherwise, please just close the issue :)

Bests,
Fran
