### ISSUE TITLE
Supplying a pre-computed STAR index to SQANTI3 QC

### ISSUE THREAD

**Issue by AbeerMM** [ConesaLab/SQANTI3#130]
Hello,

I'm trying to run SQANTI3 QC, but I keep getting this error related to STAR:

`**** Running STAR for calculating Short-Read Coverage.
START running STAR...
Running indexing...
Traceback (most recent call last):
  File "/home/ubuntu/softwares/SQANTI3/sqanti3_qc.py", line 2461, in <module>
    main()
  File "/home/ubuntu/softwares/SQANTI3/sqanti3_qc.py", line 2444, in main
    run(args)
  File "/home/ubuntu/softwares/SQANTI3/sqanti3_qc.py", line 1854, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/home/ubuntu/softwares/SQANTI3/sqanti3_qc.py", line 1493, in isoformClassification
    star_out, star_index = star(args.genome, args.short_reads, args.dir, args.cpus)
  File "/home/ubuntu/softwares/SQANTI3/utilities/short_reads.py", line 56, in star
    subprocess.call(['STAR', '--runThreadN', str(cpus), '--runMode', 'genomeGenerate', '--genomeDir', index_dir, '--genomeFastaFiles', fasta_genome, '--outTmpDir', index_dir_tmp])
  File "/home/ubuntu/miniconda2/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ubuntu/miniconda2/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/ubuntu/miniconda2/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'STAR': 'STAR'
`

It seems the error happens when indexing with STAR. I tried to use different number of CPUs (high/low) and watch the memory consumption but I still get this error.

I'd appreciate it if anyone can give me some insight to resolve this problem.

**Comment by AbeerMM** [comment]
I updated conda and git pull the repos, and it the error was resolved.

However, I'm wondering if there is a way to give the STAR index instead of re-generating it every time I run SQANTI for an individual sample?

**Comment by FJPardoPalacios** [comment]
Hi @AbeerMM ! 
It seemed that you didn't have installed STAR, maybe because by the time you build the environment it wasn't included in the YML file or maybe because of a problem with conda.

Regarding what you were asking, we haven't included yet an option to give STAR index (we take note). However, there is a way to "hack" it in the meantime: Before running SQ3, you can create the output folder and inside it create a new folder called `STAR_index`. SQANTI3 will check if that `STAR_index` exists and if it does, it will jump to the mapping.

Please, let me mark this issue as an enhancement and as soon as I implement the option of giving the STAR index, I'll close it.
Bests,

Fran

**Comment by AbeerMM** [comment]
@FJPardoPalacios Thank you so much. The hack seems to work with me. I get Nan in the column ratio_TSS. I'm not sure if that has something to do with the STAR mapping step or not. But I use fofn file for --short-read option.
