### ISSUE TITLE
Get the sequences or ids of unique genes alone

### ISSUE THREAD

**Issue by Karthickrishnan** [ConesaLab/SQANTI3#133]
Hi,

Is there any way I can get the ids or sequences of unique genes (printed on the first page of SQANTI report)?

If so, how do I get it?

Thank you,
Karthic

**Comment by FJPardoPalacios** [comment]
Please, use **associated_gene** column in the classification output. Isoforms not matching a known gene will be labeled as "novelGene_<number>", since SQ3 doesn't try to define new genes with several isoforms. I guess that you won't be interested in those genes, so the easiest way to get the list of known gene IDs is using this command in the terminal:

`cut -f7 <outputName>_classification.txt | grep -v 'novelGene' | sort -u > known_gene_IDs.txt`

Regarding their sequence, I wouldn't say that there is a single gene sequence if there are several isoforms.

Fran
