### ISSUE TITLE
Unstranded Short reads

### ISSUE THREAD

**Issue by AbeerMM** [ConesaLab/SQANTI3#135]
Hello,

I'm using short reads with SQANTI QC, but my Illumina data is unstranded. Can SQANTI work with that, or does it require stranded short reads?

Also, if I have external RNA-seq can I use them as input for short reads, or does it have to be from the same cDNA library?

Thank you

**Comment by AbeerMM** [comment]
I've tried to search for answer for this question, but I'm not sure I can find any. I hope the developer of SQANTI3 can explain this part. 

If my short reads are NOT strand-specific (but paired-end), how would that affect the analysis? I'm using SQANTI not for gene isoforms, but more for novel functional non-coding RNA. Any input on that would be helpful.

**Comment by AbeerMM** [comment]
I checked the example data attached with the package, and ran infer_experiment.py on the fastq files to see if the data is strand-specific. I got this output:
This is PairEnd Data
Fraction of reads failed to determine: 0.0792
Fraction of reads explained by "1++,1--,2+-,2-+": 0.0133
Fraction of reads explained by "1+-,1-+,2++,2--": 0.9076

which means, the data is stand specific and explained by the second read. So, my question, what will be signficantly affected if I use unstranded pair-end short reads with SQANTI3?

**Comment by carolinamonzo** [comment]
Hi @AbeerMM, 
Since STAR generates an SJ.out.tab file regardless of using stranded or unstranded data, I don't see a problem using unstranded short reads to support the long reads. Isoform quantification with unstranded reads would be problematic in assigning reads to the incorrect strand and quantifying antisense isoforms instead of the sense isoform (or the other way around). But if you are only using the reads to support the splice junctions, no problem. 👍
