### ISSUE TITLE
The coordinates of isoform in gtf are not the same as CDS genomic start and end in the output from Sqanti3

### ISSUE THREAD

**Issue by Dongxu-Zheng** [ConesaLab/SQANTI3#137]
Hi, thank you for developing such great software! I am now working on two Pacbio Isoseq samples. I noticed that the coordinates of the isoform in the gtf are not the same as the coordinates from the Sqanti3 output after running sqanti3_qc.py and sqanti3_RulesFilter.py. I am not sure how to interpret the different coordinates?

Here are some examples:
![image](https://user-images.githubusercontent.com/65728158/161447466-71eec7e9-f6c2-490d-877f-93ef40cb66f0.png)

V4 and V5 are the coordinates of the isoforms from the gtf file. The last two columns are the coordinates from the sqanti3 output.

Many thanks for any suggestions!

Cheers,
Dongxu Zheng

**Comment by aarzalluz** [comment]
Hi @Dongxu-Zheng,

The last two columns refer to the start and end of the CDS (not to be mistaken with the start and end of the transcript). The CDS is the predicted coding region of the transcript. If these are NA, it is probably because no coding region was predicted and therefore the isoform should be marked as non-coding.

Ángeles
