### ISSUE TITLE
ERROR:Running calculation of TSS ratio

### ISSUE THREAD

**Issue by 377079200** [ConesaLab/SQANTI3#156]
Dear SQUANTI authors,
I am running your pipeline with my actual dataset. It was working smoothly until the calculation of TSS ratios, when following error occurred:
`python ~/GitPublish/SQANTI3/sqanti3_qc.py ~/rna_seq/short_reads/corrected/gfa/mix_gtf/merge_gtf/end/A2_strand_gffcom.gtf ~/nanopore_drs/drs_input/Genome/A2/change.Chr_genome_final_gene.gtf ~/nanopore_drs/drs_input/Genome/A2/A2.Chr.fa -o test -d A2 --short_reads ~/rna_seq/short_reads/corrected/A2/A2.list.fofn --expression ~/rna_seq/short_reads/corrected/gfa/mix_gtf/merge_gtf/isoform_count/A2_iso_tpm.txt -c /public/home/rpwang/rna_seq/short_reads/corrected/gfa/STAR_junction/A2_Req1SJ.out.tab,/public/home/rpwang/rna_seq/short_reads/corrected/gfa/STAR_junction/A2_Req2SJ.out.tab --cpus 6 --report both --isoAnnotLite`
ERROR:
`R scripting front-end version 4.1.3 (2022-03-10)
WARNING: output directory /public/home/rpwang/nanopore_drs/drs_out/sqanti/A2 already exists. Overwriting!
Write arguments to /public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/test.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /public/home/rpwang/nanopore_drs/drs_input/Genome/A2/A2.Chr.fa....
Error corrected FASTA /public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/test_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
ORF file /public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/test_corrected.faa already exists. Using it....
**** Parsing Reference Transcriptome....
/public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/refAnnotation_test.genePred already exists. Using it.
**** Parsing Isoforms....
**** Running STAR for calculating Short-Read Coverage.
START running STAR...
Index identified. Proceeding to mapping.
Input pattern: /public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/STAR_mapping/.
The following files found and to be read as junctions:
/public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/STAR_mapping/A2_RNA_Rep1_R1_cleaned.corSJ.out.tab
/public/home/rpwang/nanopore_drs/drs_out/sqanti/A2/STAR_mapping/A2_RNA_Rep2_R1_cleaned.corSJ.out.tab
483758 junctions read. 835 junctions added to both strands because no strand information from STAR.
Running calculation of TSS ratio
Traceback (most recent call last):
  File "/public/home/rpwang/GitPublish/SQANTI3/sqanti3_qc.py", line 2471, in <module>
    main()
  File "/public/home/rpwang/GitPublish/SQANTI3/sqanti3_qc.py", line 2454, in main
    run(args)
  File "/public/home/rpwang/GitPublish/SQANTI3/sqanti3_qc.py", line 1858, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/public/home/rpwang/GitPublish/SQANTI3/sqanti3_qc.py", line 1529, in isoformClassification
    inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order)
  File "/public/home/rpwang/GitPublish/SQANTI3/utilities/short_reads.py", line 127, in get_TSS_bed
    strand=str(loc[2])
IndexError: list index out of range
`
I am not really sure what caused this problem.
Would be grateful for your support.

Best regards,

Mark

**Comment by albyrne0815** [comment]
Hi,

I've also ran into an error regarding calculation of the TSS ratio in my case it looks like it related to bedtools. 

**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /gne/data/dnaseq/analysis/byrne/refs/10X_gex-GRCh38-2020-A-Human/refdata-gex-GRCh38-2020-A/fasta/genome.fa....
Error corrected FASTA /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/10Mr2c2_Mando_Sqanti_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
ORF file /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/10Mr2c2_Mando_Sqanti_corrected.faa already exists. Using it....
**** Parsing Reference Transcriptome....
/gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/refAnnotation_10Mr2c2_Mando_Sqanti.genePred already exists. Using it.
**** Parsing Isoforms....
**** Reading Splice Junctions coverage files.
Input pattern: /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/COV504.SJ.out.tab,/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/IGROV1.SJ.out.tab,/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/SRR18539091_SJ.out.tab.
The following files found and to be read as junctions:
/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/COV504.SJ.out.tab
/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/IGROV1.SJ.out.tab
/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/SRR18539091_SJ.out.tab
833344 junctions read. 1537 junctions added to both strands because no strand information from STAR.
Using provided BAM files for calculating TSS ratio
Traceback (most recent call last):
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 2471, in <module>
    main()
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main
    run(args)
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 1858, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 1520, in isoformClassification
    inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order)
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/utilities/short_reads.py", line 150, in get_TSS_bed
    i.sort(g=chr_order, output=inside_sorted)
  File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/bedtool.py", line 923, in decorated
    result = method(self, *args, **kwargs)
  File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/bedtool.py", line 402, in wrapped
    stream = call_bedtools(
  File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools sort -i /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/coverage_inside_TSS.bed_tmp -g /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Bulk_COV5O4/chr_order.txt

Error message was:

*****ERROR: Unrecognized parameter: -g *****


*****ERROR: Unrecognized parameter: /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Bulk_COV5O4/chr_order.txt *****

**Comment by 377079200** [comment]
Hi, I don't get an error about bedtools, I still don't understand what's wrong

**Comment by KMbio43** [comment]
> Hi,
> 
> I've also ran into an error regarding calculation of the TSS ratio in my case it looks like it related to bedtools.
> 
> **** Running SQANTI3... **** Parsing provided files.... Reading genome fasta /gne/data/dnaseq/analysis/byrne/refs/10X_gex-GRCh38-2020-A-Human/refdata-gex-GRCh38-2020-A/fasta/genome.fa.... Error corrected FASTA /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/10Mr2c2_Mando_Sqanti_corrected.fasta already exists. Using it... **** Predicting ORF sequences... ORF file /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/10Mr2c2_Mando_Sqanti_corrected.faa already exists. Using it.... **** Parsing Reference Transcriptome.... /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/refAnnotation_10Mr2c2_Mando_Sqanti.genePred already exists. Using it. **** Parsing Isoforms.... **** Reading Splice Junctions coverage files. Input pattern: /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/COV504.SJ.out.tab,/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/IGROV1.SJ.out.tab,/gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/SRR18539091_SJ.out.tab. The following files found and to be read as junctions: /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/COV504.SJ.out.tab /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/IGROV1.SJ.out.tab /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Star_SJs/SRR18539091_SJ.out.tab 833344 junctions read. 1537 junctions added to both strands because no strand information from STAR. Using provided BAM files for calculating TSS ratio Traceback (most recent call last): File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 2471, in main() File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main run(args) File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 1858, in run isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF) File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_qc.py", line 1520, in isoformClassification inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order) File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/utilities/short_reads.py", line 150, in get_TSS_bed i.sort(g=chr_order, output=inside_sorted) File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/bedtool.py", line 923, in decorated result = method(self, *args, **kwargs) File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/bedtool.py", line 402, in wrapped stream = call_bedtools( File "/gstore/home/byrnea6/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/pybedtools/helpers.py", line 460, in call_bedtools raise BEDToolsError(subprocess.list2cmdline(cmds), stderr) pybedtools.helpers.BEDToolsError: Command was:
> 
> ```
> bedtools sort -i /gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_Mando/coverage_inside_TSS.bed_tmp -g /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Bulk_COV5O4/chr_order.txt
> ```
> 
> Error message was:
> 
> *****ERROR: Unrecognized parameter: -g *****
> 
> *****ERROR: Unrecognized parameter: /gne/data/dnaseq/analysis/byrne/Nanopore_Raw_Data/Projects/Ovarianlines/Short_Read_Data/bulk_RNAseq/Bulk_COV5O4/chr_order.txt *****

I had the same problem. How did you solve it? 
Running calculation of TSS ratio
Traceback (most recent call last):
  File "/home/MK/biosoft/SQANTI3/sqanti3_qc.py", line 84, in <module>
    main()
  File "/home/MK/biosoft/SQANTI3/sqanti3_qc.py", line 68, in main
    run(args)
  File "/home/MK/biosoft/SQANTI3/src/qc_pipeline.py", line 84, in run
    ratio_TSS_dict = TSS_ratio_calculation(args.SR_bam, args.short_reads, star_out,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/MK/biosoft/SQANTI3/src/classification_preprocessing.py", line 72, in TSS_ratio_calculation
    inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/MK/biosoft/SQANTI3/src/utilities/short_reads.py", line 169, in get_TSS_bed
    i.sort(g=chr_order, output=inside_sorted)
  File "/home/MK/anaconda3/envs/sqanti3/lib/python3.11/site-packages/pybedtools/bedtool.py", line 907, in decorated
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/MK/anaconda3/envs/sqanti3/lib/python3.11/site-packages/pybedtools/bedtool.py", line 388, in wrapped
    stream = call_bedtools(
             ^^^^^^^^^^^^^^
  File "/home/MK/anaconda3/envs/sqanti3/lib/python3.11/site-packages/pybedtools/helpers.py", line 456, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

        bedtools sort -i /home/MK/biosoft/SQANTI3/example/SQANTI3_QC_output22/coverage_inside_TSS.bed_tmp -g example/SQANTI3_QC_output22/STAR_index//chrNameLength.txt

Error message was:

*****ERROR: Unrecognized parameter: -g *****


*****ERROR: Unrecognized parameter: example/SQANTI3_QC_output22/STAR_index//chrNameLength.txt *****


Tool:    bedtools sort (aka sortBed)
Version: v2.25.0
Summary: Sorts a feature file in various and useful ways.
