### ISSUE TITLE
Handling factor columns error during sqanti_filter.py ML

### ISSUE THREAD

**Issue by kudasonya** [ConesaLab/SQANTI3#158]
Hello! Thank you for such a great tool. I am trying to run the new ML algorithm and am getting this error. Running the old version of sqanti_filter doesn't cause any errors. 

```
python SQANTI3/sqanti3_filter.py ML chr12_13_sqanti_out/capture_classification.txt \
--gtf chr12_13_sqanti_out/capture_corrected.gtf -d SQANTI3_ML_out --skip_report --filter_mono_exonic
```

ML DATA PREPARATION:

Aggregating FL counts across samples (if more than one sample is provided)...

Replacing NAs with appropriate values for ML...

Handling factor columns...
Error in `[.data.frame`(d1, , x) : undefined columns selected
Calls: as.factor -> is.factor -> [ -> [.data.frame
Execution halted

Running SQANTI3 filtering...

/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/SQANTI3.env/bin/Rscript /ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/utilities/filter/SQANTI3_MLfilter.R -c /ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/chr12_13_sqanti_out/capture_collapsed_classification.txt -o capture_split_2pass_3_collapsed -d SQANTI3_ML_out -t 0.8 -j 0.7 -i 60 -f False     -e True -m False -z 3000
Traceback (most recent call last):
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_filter.py", line 263, in <module>
    main()
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_filter.py", line 249, in main
    ids, inclusion_file = run_ML(args)
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_filter.py", line 125, in run_ML
    seqs_to_keep = set(line.strip() for line in open(inclusion_list))
FileNotFoundError: [Errno 2] No such file or directory: 'SQANTI3_ML_out/capture_collapsed_inclusion-list.txt'

**Comment by albyrne0815** [comment]
Hi, I've also had the same error as well. See below:

── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): parameter, value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in `dplyr::mutate()`:
! Problem while computing `structural_category = ... %>% ...`.
Caused by error in `factor()`:
! object 'structural_category' not found
Backtrace:
     ▆
  1. ├─classif %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr:::mutate.data.frame(...)
  4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  5. │   ├─base::withCallingHandlers(...)
  6. │   └─mask$eval_all_mutate(quo)
  7. ├─... %>% ...
  8. ├─forcats::fct_relevel(...)
  9. │ └─forcats:::check_factor(.f)
 10. ├─forcats::fct_recode(...)
 11. │ └─forcats:::check_factor(.f)
 12. ├─base::factor(structural_category)
 13. └─base::.handleSimpleError(...)
 14.   └─dplyr h(simpleError(msg, call))
 15.     └─rlang::abort(...)
Execution halted
Traceback (most recent call last):
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_filter.py", line 263, in <module>
    main()
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_filter.py", line 249, in main
    ids, inclusion_file = run_ML(args)
  File "/gnet/is1/p04/data/dnaseq/analysis/byrne/SQANTI3-5.0/sqanti3_filter.py", line 125, in run_ML
    seqs_to_keep = set(line.strip() for line in open(inclusion_list))
FileNotFoundError: [Errno 2] No such file or directory: '/gne/data/dnaseq/analysis/byrne/SQANTI3-5.0/runs/10M_r2c2_isoforms/10M_StringTie/filtered/10Mr2c2_Sqanti_Stringtie_filt_inclusion-list.txt'

**Comment by kudasonya** [comment]
Hi @albyrne0815 , 
I think I got that error as I was running filter.py on a class file generated with previous version of sqanti, so the column names did not match. Rerunning sqanti_qc with v.5.0 solved the issue. 
Best wishes, 
Sofia

**Comment by jchang97** [comment]
Hi there,

SQANTI v5.1 ML works fine with default parameters, but when I include -f FORCE_FSM_IN, it generates this error for me (as below - similar to the case above). The classification.txt files and/or randomforest.RData objects have also been generated with v5.1. 

```
â„¹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in `dplyr::mutate()`:
! Problem while computing `structural_category = ... %>% ...`.
Caused by error in `factor()`:
! object 'structural_category' not found
Backtrace:
```
Could I please have some guidance on this? 

Many thanks!

**Comment by aarzalluz** [comment]
Hi @jchang97 -would you mind opening a new issue for this? This one was already closed as solved, plus you seem to be running into a different error and it should be handled separately. Thanks!
