### ISSUE TITLE
filter script (sqanti3_filter.py) of v5 is not working.

### ISSUE THREAD

**Issue by unique379r** [ConesaLab/SQANTI3#159]
Hi 
I have updated the v5 and try to use your new script i.e. sqanti3_filter.py after the sqanti3_qc.py but getting errors in both cases (rules and ML). I think its crashing in same stage and getting ZERO bytes of filter gff without any report.pdf/html.

**Command ML**

```
$sqantibin/sqanti3_filter.py ML --isoAnnotGFF3 $tapp -o testSample -d sqanti_MLfilt MMSQANTI3Annotation/testSample_classification.txt

```

**Errors**

```
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning messages:
1: Problem while computing `structural_category = ... %>% ...`.
ℹ Unknown levels in `f`: genic_intron
2: Problem while computing `structural_category = ... %>% ...`.
ℹ Unknown levels in `f`: Genic intron
Loading required package: ggplot2

Generating common filter plots...

`summarise()` has grouped output by 'gene_type', 'all_artifacts'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'structural_category'. You can override using the `.groups` argument.
Error in `$<-.data.frame`(`*tmp*`, "call_text", value = c("... %>% ...",  :
  replacement has 13 rows, data has 12
Calls: %>% ... withCallingHandlers -> <Anonymous> -> .Call -> cut -> cut.default
Execution halted
Output written to: sqanti_MLfilt/testSample.filtered.gff3

```

**Command rules**

```
$sqantibin/sqanti3_filter.py rules --isoAnnotGFF3 $tapp -o testSample -d sqanti_rulesfilt MMSQANTI3Annotation/testSample_classification.txt
```

**Errors**

```
Generating common filter plots...

`summarise()` has grouped output by 'gene_type', 'all_artifacts'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'structural_category'. You can override using the `.groups` argument.
Error in `$<-.data.frame`(`*tmp*`, "call_text", value = c("... %>% ...",  :
  replacement has 13 rows, data has 12
Calls: %>% ... withCallingHandlers -> <Anonymous> -> .Call -> cut -> cut.default
Execution halted
Output written to: sqanti_rulesfilt/testSample.filtered.gff3
```

Second Question:

**Can you please clear to me the input options of fasta, gtf and faa, i assume its the output of sqanti3_qc.py which generates corrected.fasta , corrected.gff and corrected.faa. am i right ?**

**Comment by aarzalluz** [comment]
Hi @unique379r,

Regarding your first question, it seems that the script is crashing at the report stage. Could you run the filters with the `--skip_report` flag enabled so that we can verify that?

As for your second question, yes -you may supply any of the files output by SQANTI3 QC. Note that these are not mandatory arguments for the filter, therefore, you could just supply the GTF, for instance, if you only needed to filter that file for downstream analysis.

Best,

Ángeles

**Comment by unique379r** [comment]
Hi Ángeles
Thank you for your suggestions, yes i tried and that seem worked but in both cases (ML and rules), got zero byte of testSample.filtered.gff3. 

346 sqanti_ML/testSample_params.txt
536 sqanti_ML/testSample_TN_list.txt
541 sqanti_ML/testSample_TP_list.txt
1.1M sqanti_ML/testSample_MLresult_classification.txt
1.9K sqanti_ML/testSample_inclusion-list.txt
0 sqanti_ML/testSample.filtered.gff3


1.1M sqanti_rules/testSample_RulesFilter_result_classification.txt
3.9K sqanti_rules/testSample_inclusion-list.txt
28K sqanti_rules/testSample_filtering_reasons.txt
0 sqanti_rules/testSample.filtered.gff3

# Note: This is actually a test data that i am testing, do you think that might have an impact ?  Asking as previous error says : replacement has 13 rows, data has 12. 

Please advice.
Thanks

**Comment by aarzalluz** [comment]
Hi @unique379r,

It seems that SQANTI3 is correctly generating an inclusion list. Since the GFF3 file is empty, it may be an issue with all transcripts being classified as artifacts due to the dataset being too small -can you verify this?

As for the report error, it looks like your test data does not have isoforms form all of SQ3 categories -hence the 13 vs 12 row error- but this is just me guessing. You can try to generate another test dataset taking this into consideration, or try with the whole dataset and see whether the error persists.

Best,

Ángeles

**Comment by unique379r** [comment]
Hi
I tested it again and log says it does have some artifacts but there are useful isoforms as well, see the logs bellow by ML:

-------------------------------------------------

Applying intra-priming filter to our dataset.

Intra-priming filtered transcripts:

FALSE  TRUE
   84    38

 -------------------------------------------------

Writing filter results to classification file...

	Wrote filter results (ML and intra-priming) to new classification table:
	testSample_MLresult_classification.txt file.

	Wrote isoform list (classified as non-artifacts by both ML and intra-priming
	filters) to testSample_inclusion-list.txt file

-------------------------------------------------

SUMMARY OF MACHINE LEARNING + INTRA-PRIMING FILTERS:

Artifact  Isoform
      38       84

###Therefore its should generate the gff3 atleast. clearly the filter script does have bugs to generate the gff3 as well as well as pdf report. By the way, why did u remove report option to choose html or pdf or both similar you have in QC script ?

**Comment by aarzalluz** [comment]
Hi @unique379r,

After reading through your logs and based on the information you have provided, here are a few points that you may want to consider:

- You seem to be running the filter on a set of ~100 transcripts. I would strongly recommend running the filter with a larger set in order to see a behaviour that is more close to reality, both computationally and in terms of interpretation. Since the script did not produce any errors, in spite of the GFF3 being empty, it would be wise to run a few more tests before affirming that this as a bug. The example dataset that is included in SQANTI3 is always a good place to start playing around with the different scripts and getting to know the tool.

- The filter script is designed to produce two outputs: 1) a new classification table and 2) an inclusion list. This means that, if you do not provide a GFF3, no GFF3 will be generated. The same is true for GTF, FASTA, etc. Basically, SQ3 will just filter whatever input files you supply based on the result of the filter. This was just done to make user's life easier -it is still possible for you to use the inclusion list file to filter the GFF3.

- Please take into account that, as previously stated, this information and all of the inner workings of the SQANTI3 filter are fully described in [the SQANTI3 wiki]. We strongly advise reading carefully through the documentation before running the tool, as it is made to be as comprehensive as possible in order to save users time and energy when getting to know SQANTI3.

 - For future reference, when opening an issue, it is useful for developers to show a small chunk of your input files so that we can understand how you are running the tool and get to the bottom of the error.

Given that the tool is finishing with no error and that you can use the workaround described above to filter the GFF3, I will now close the issue. 

Best,

Ángeles
