### ISSUE TITLE
Gene classification includes too few annotated genes

### ISSUE THREAD

**Issue by joelnitta** [ConesaLab/SQANTI3#161]
This may be difficult to fix without providing data, so please let me know and I will send data files separately.

I am using SQANTI3 after the cDNA cupcake pipeline for isoforms (input is collapsed, filtered GFF3). I am not using most options of SQANTI3: just the mandatory isoforms, genome annotation, and genome fasta, along with "--isoAnnotLite". The input includes 61,472 unique isoforms. In previous runs, many of these mapped to annotated genes. However, in my current run, in the report under "Gene Classification" I only get 1 annotated gene and 1,214 novel genes. This is despite many of the transcripts being FSM (15,646) or ISM (8,128).

I would greatly appreciate any tips on how to fix this! Thanks!

Sqanti v5.0 (docker image: joelnitta/sqanti3:5.0)

**Comment by FJPardoPalacios** [comment]
Hi @joelnitta ,

That's a pretty funny issue. I would say that's something related to your reference genome annotation...

When you activate the `--isoAnnotLite` option, SQANTI3 also activates automatically the `--genename` one. We forced this because pre-computed tappAS-compatible files use gene names instead of gene IDs (gene names are more useful for the purpose of tappAS GUI). Maybe some of your annotated transcripts are associated to the same gene name, but they have different gene IDs or maybe they simply do not have a gene name. Please, take a look to your annotation file and check out that all the different gene IDs have a different gene name.

If you want to run it and you don't mind to have gene IDs in your final tappAS-compatible GFF3, I would suggest to replace in your reference annotation file all the gene names with their matching gene IDs. 

```
chr22	HAVANA	transcript	10939388	10961338	.	-	.	gene_id "ENSG00000283047.1"; transcript_id "ENST00000635667.1"; gene_name "FRG1FP";
```
should become...
```
chr22	HAVANA	transcript	10939388	10961338	.	-	.	gene_id "ENSG00000283047.1"; transcript_id "ENST00000635667.1"; gene_name "ENSG00000283047.1";
```


That will make SQANTI3 to reproduce your previous runs and at the same time create a tappAS-compatible GFF3 file with different genes and not only one.

As all this is just a guess of what could be going on, let me know if this is your case and if it fixed your problem.

Bests,
Fran

**Comment by joelnitta** [comment]
Thanks @FJPardoPalacios! You are indeed correct: my GTF file had `gene` instead of `gene_name`.

The problem could be resolved either by omitting `--isoAnnotLite` or by changing all instances of `gene` in the GTF file to `gene_name`.

Thanks again for your help, I would not have been able to figure this out otherwise!
