### ISSUE TITLE
Error generating the report pdf

### ISSUE THREAD

**Issue by LilFish15** [ConesaLab/SQANTI3#165]
Hi, 

I could use your help troubleshooting this! Thank you so much! 

THE COMMAND I RUN:
sqanti3_qc.py SD_anox.collapsed.gff SDv2.2_Gene_annot.gtf SDv2.2_Chromosomes.fasta -o sqanti_out3 --report pdf

THE ERROR MESSAGE:
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
Error in `[<-.data.frame`(`*tmp*`, which(x$diff_to_gene_TSS <= 50), "Annotation",  : 
  replacement has 1 row, data has 0
Calls: [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "/local/cluster/SQANTI3/bin/sqanti3_qc.py", line 2490, in <module>
    main()
  File "/local/cluster/SQANTI3/bin/sqanti3_qc.py", line 2473, in main
    run(args)
  File "/local/cluster/SQANTI3/bin/sqanti3_qc.py", line 2057, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/local/cluster/SQANTI3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/local/cluster/SQANTI3/bin/Rscript /local/cluster/SQANTI3-5.1/utilities//report_qc/SQANTI3_report.R /nfs0/IB/Barreto_Lab/scratch/marine/1_pacbio/sqanti3/sqanti_out3_classification.txt /nfs0/IB/Barreto_Lab/scratch/marine/1_pacbio/sqanti3/sqanti_out3_junctions.txt /nfs0/IB/Barreto_Lab/scratch/marine/1_pacbio/sqanti3/sqanti_out3.params.txt /local/cluster/SQANTI3-5.1/utilities False pdf' returned non-zero exit status 1.

**Comment by aarzalluz** [comment]
Hi @LilFish15,

Could you provide more details regarding your SQANTI3 run? This R error doesn't say much. There seems to be some sort of problem with the filtering of the `diff_to_gene_TSS` column in the `classification.txt` file, apparently due to no values in the column being <=50, but that's it. 

This leads me to think that there might be some other problem in the processing of your transcripts, perhaps due to the selection of an incorrect reference genome/GTF file, since there are no close matches in the TSS found in your reference transcriptome annotation. However, this is just a guess based on that single error.

Are there any other messages/warnings/errors earlier in the SQANTI3 QC log that may indicate that something is wrong?

Best,

Ángeles
