### ISSUE TITLE
Full-splice_match transcripts with fusion gene ID?

### ISSUE THREAD

**Issue by lyc-1995** [ConesaLab/SQANTI3#166]
Hello, SQANTI3 team.
  I'm using `sqanti3_qc.py` from `SQANTI3 v5.1` to annotate my IsoSeq transcripts against the annotation. I got some transcripts with reference IDs (for example `ENST00000654015`) and annotated as `full-splice_match`, whose gene ID, however, were formatted like fusion genes (`ENSG00000224699_ENSG00000162775`).  

A `classification.txt` file has been uploaded here, and `PB.5212.10`  on line `5261` is  one example of the transcripts I mentioned above.

```
5261:PB.5212.10	1	+	2354	2	full-splice_match	ENSG00000224699_ENSG00000162775	ENST00000654015	3214	2	1317	-457	1276	453	alternative_3end5end	FALSE	canonical	NA	NA	NA	NA  NA	NA	FALSE	NA	NA	NA	A	coding	460	1383	192	1574	110340933	110346354	FALSE	50.0	AAAAGAAGGAGAAATGCTCC	NA	NA	NA	NA	NA	NA	GYGKATPTTRLWVGGLGPWVPLAALAREFDRFGTIRTIDYRKGDSWAYIQYESLDAAHAAWTHMRGFPLGGPDRRLRVDFADTEHRYQQQYLQPLPLTHYELVTDAFGHRAPDPLRGARDRTPPLLYRDRDRDLYPDSDWVPPPPPVRERSTRTAATSVPAYEPLDSLDRRRDGWSLDRDRGDRDLPSSRDQPRKRRLPEESGGRHLDRSPESDRPRKRHCAPSPDRSPELSSSRDRYNSDNDRSSRLLLERPSPIRDRRGSLEKSQGDKRDRKNSASAERDRKHRTTAPTEGKSPLKKEDRSDGSAPSTSTASSKLKSPSQKQDGGTAPVASASPKLCLAWQGMLLLKNSNFPSNMHLLQGDLQVASSLLVEGSTGGKVAQLKITQRLRLDQPKLDEVTRRIKVAGPNGYAILLAVPGSSDSRSSSSSAASDTATSTQRPLRNLVSYLKQKQAAGVISLPVGGNKDKENTGVLHAFPPCEFSQQFLDSPAKALAKSEEDYLVMIIVRAKLVEQRMKIWNSKL	NA
```
[dedup.5merge.collapsed_classification.filtered_lite_classification.txt.gz](https://github.com/ConesaLab/SQANTI3/files/9451175/dedup.5merge.collapsed_classification.filtered_lite_classification.txt.gz)

My question:
1. Is there something wrong? How should I treat the novelty of gene annotation from transcripts like this?
2. Or should I treat these transcripts as actually known transcripts from already annotated genes? for example, `ENST00000654015` from `ENSG00000162775`?

**Comment by aarzalluz** [comment]
Hi @lyc-1995,

I believe what is happening is that those fusion genes are present in your reference transcriptome annotation, so there might be transcripts that are detected as FSM of isoforms from those genes. This is not really a problem, since reference annotations such as RefSeq usually include these type of genes when they are sufficiently well-characterized. If you do not wish for this to happen, you may want to consider using a different reference transcriptome to characterize your transcripts, or modifying your current one to remove fusion genes.

Best,

Ángeles

**Comment by aarzalluz** [comment]
Hi @lyc-1995,

After discussing this with @FJPardoPalacios, we came up with an alternative explanation. SQ3 associates reference genes (and transcripts, where applicable) following parallel paths. This means that your transcripts may have been assigned to the two genes (`ENSG00000224699` and `ENSG00000162775`) due to the fact that it partially overlaps both, however, when assigning a reference transcript, SQ3 finds that it shares all its junctions with `ENST00000654015`, which belongs to one of these genes. `PB.5212.10` is has been classified under the alternative 3' and 5' end subcategory, which may explain the additional variability allowing for overlap with two nearby genes. You may be able to verify all this by loading your IsoSeq3 GTF file on GenomeBrowser and comparing it to the annotation.

In this case, SQANTI's interpretation of the reality of the transcripts and the genes is technically correct (even if slightly confusing).

I'm leaving the issue open for now, but please do confirm if this solves your question so that we can close it.

Best,

Ángeles
