### ISSUE TITLE
Different number of annotated genes in QC vs filter

### ISSUE THREAD

**Issue by jchang97** [ConesaLab/SQANTI3#167]
Thank you for this amazing tool!

I just have a question regarding the different number of annotated genes within the reports generated by the SQANTI-QC and SQANTI-filter. 

This is the output from the QC: Annotated Genes=13,201
![image](https://user-images.githubusercontent.com/41040156/191382016-c4b4bfdf-d208-4352-bb2a-0d4a8c08bedf.png)

And this is the output from filter via the ML pathway: Annotated Genes = 13,195

![image](https://user-images.githubusercontent.com/41040156/191382098-00be4c03-5d27-4a87-b272-c80b61897f07.png)

The number of novel genes and total number of transcripts appear to be the same. Could you please help me understand why this might be happening? I am using SQANTI3 v5.1.

Thank you very much :)

**Comment by FJPardoPalacios** [comment]
Wow, this might be a funny bug. I just checked some of my reports and I always get the same number of annotated genes in both.
Code is not the same for the QC report and filter report, maybe there is a couple of weird gene names that are creating this issue. First of all, let's do one thing: check the number of annotated genes in the classification files you obtained from the QC and the filter. You can do it with this command:

`cut -f7 *_classification.txt | sort -u | grep -v 'associated_gene' | grep -v 'novel' -c `

You should get in both cases the same number since both classification files are almost the same (the filter one contains a few columns more, but the rest shouldn't be changed). If you don't get the same amount of genes, then something happened to your file between one step and the other...

Bests,
Fran

**Comment by jchang97** [comment]
Hi Fran,

Thank you for your reply!

I've used the command as above and here are my results from running on the QC classification.txt file and the ML filter classification.txt file:

```
$ cut -f7 "/data/gpfs/projects/punim1466/analysis/nanopore/isoform/sqanti/libE/new_gtf/libE_classification.txt" | sort -u | grep -v 'associated_gene' | grep -v 'novel' -c
13195
$ cut -f7 "/data/gpfs/projects/punim1466/analysis/nanopore/isoform/sqanti/libE/new_gtf/filter_libE_ML_MLresult_classification.txt" | sort -u | grep -v 'associated_gene' | grep -v 'novel' -c
13195

```

So they both seem to match up which is great, and match the annotated gene number reported in the ML report. Please let me know if there's anything else I should try. 

Thank you

**Comment by FJPardoPalacios** [comment]
Okay, definitively your transcriptome contains 13915 known genes. I don't really know what happened in the QC report, but it should have printed 13915 too. It seems that there are 6 known "associated_genes" that are being counted twice for some unknown reason... But at the end of the day, you have 13915 different known genes :)

Bests,
Fran

**Comment by jchang97** [comment]
Awesome thank you so much for confirming, really appreciate it!

**Comment by trista1115** [comment]
Hi

I had met the same issue by using default rules, how should I get the right number in pdf file for both QC and filter step?

Thanks in advance!
