### ISSUE TITLE
Keyerror 1172

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#175]
Hi, I was wondering if there is any thought regarding a reported Keyerror 1172. Below is the tracing. There is still output of the sqanti3_qc.py, but seems a smaller size than usual. Thanks

**** Parsing Isoforms....
Process Process-4:
Traceback (most recent call last):
  File "/project/conda_envs/SQANTI3.env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/project/conda_envs/SQANTI3.env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/project/SQANTI3-4.2/sqanti3_qc.py", line 1902, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/project/SQANTI3-4.2/sqanti3_qc.py", line 1734, in isoformClassification
    isoform_hit.CDS_genomic_start = m[isoform_hit.CDS_start-1] + 1  # make it 1-based
KeyError: 1172

**Comment by xiaonalu** [comment]
I updated the SQANTI3 version to 5.1, but it still report the same error. It seems data related, not happen to all my data. Thanks

**Comment by almart7** [comment]
Hello @xiaonalu, we are working on your issue and will answer as soon as possible. Sorry for the inconvenience!

**Comment by aarzalluz** [comment]
Hi @xiaonalu -in order to address your problem, we would need more info regarding how you run SQANTI3, your input data, etc. However, since you said the issue is data-related, perhaps could you try to re-run the dataset after removing the offending transcript(s). By looking at the error message, it seems like there might be a problem with how some trancript coordinates are defined in the GTF?

**Comment by aarzalluz** [comment]
Closing as not reproducible -and potentially data-related-, may reopen if OP provides further details.

**Comment by socialhang** [comment]
Hello， I have same problem. @aarzalluz @almart7 @xiaonalu 

And I will upload my data to check it ! 

data：
[chr3.1.tar.gz](https://github.com/user-attachments/files/15937124/chr3.1.tar.gz)

command:
`python sqanti3_qc.py chr3.1FL0.fa chr3.1.gtf chr3.1.bed.fa--force_id_ignore --fasta -t 64`

errors:
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** TSS ratio will not be calculated since SR information was not provided
**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "/work/home/acg43aksd4/software/SQANTI3/sqanti3_qc.py", line 2577, in <module>
    main()
  File "/work/home/acg43aksd4/software/SQANTI3/sqanti3_qc.py", line 2560, in main
    run(args)
  File "/work/home/acg43aksd4/software/SQANTI3/sqanti3_qc.py", line 1875, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF, star_out, star_index, SJcovNames, SJcovInfo)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acg43aksd4/software/SQANTI3/sqanti3_qc.py", line 1706, in isoformClassification
    isoform_hit.CDS_genomic_start = m[isoform_hit.CDS_start-1] + 1  # make it 1-based
                                    ~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 276
