### ISSUE TITLE
Difference between genic_intron and intergenic classification 

### ISSUE THREAD

**Issue by NLykoskoufis** [ConesaLab/SQANTI3#177]
Hello, 

I am using SQANTI3 qc to classify transcripts and I have a question regarding the difference between genic_intron and intergenic transcript classification. From my understanding `genic_intron` refers to a transcript that is overlapping an intron of a gene whereas `intergenic` refers to a transcript that does not overlap a gene at all. However, if we look at the attached IGV, we can see that both intergenic (dark yellow) and genic_intron (dark red) appear to be both in intronic regions (dark blue, gencode annotation hg38, v33). Thus, I wanted to ask you whether there is any particular distinction between these two categories.

Thanks in advance!
Nikos

![Screenshot from 2023-01-03 09-43-00](https://user-images.githubusercontent.com/26184609/210324240-80944a70-458d-4bec-a52b-ebaa7c0db98c.png)

**Comment by almart7** [comment]
Hello @NLykoskoufis , we are working on your issue and will answer as soon as possible. Sorry for the inconvenience!

**Comment by almart7** [comment]
Hello @NLykoskoufis, did you get both results from the same execution? If they come from different executions, have you checked that you used the same annotation both times?

**Comment by NLykoskoufis** [comment]
Hello @almart7, they both are coming from the same execution using the same annotation. I've just separated intergenic and genic_intron transcripts into two separate gtf files for visualization purposes.

**Comment by defendant602** [comment]
I have the same issue, I find that when a mono-exon thanscript (may be artifacts) was totally contained (same strand) in an intron of a reference transcript, it will be classified as intergenic.

**Comment by FJPardoPalacios** [comment]
Hi @NLykoskoufis ,
I'm curious about how you separated Intergenic and Genic Intron isoforms, because some PB IDs (i.e. PB.36340.274 or PB.36340.278) can be found in both GTFs, but with different appearances (all the intergenic seem to be mono-exon, but PB.36340.274 has 2 exons in the other track). Maybe there was some problem parsing the initial GTF.

Anyway, regarding your issue and the stated by @defendant602, I just checked the code and I found a bug in the definition of Genic Intron category. The problem should be fixed now, so please download the latest version of SQ3 and run it again to see if the problem has been solved. Let me know if anything went wrong, otherwise, close the issue please :)

Bests,
Fran

**Comment by aarzalluz** [comment]
Hi @NLykoskoufis and @defendant602,

We just released a SQ3 patch that includes the bug fix, you can download the new version [here](https://github.com/ConesaLab/SQANTI3/releases/tag/v5.1.1).

Best,

Ángeles
