### ISSUE TITLE
How to set seed in ML filter?

### ISSUE THREAD

**Issue by cjy-23** [ConesaLab/SQANTI3#179]
Hello, 

Thank you for this amazing tool!

Just wondering how we can set some kind of seed to make sure we can reproduce randomforest.RData when we use the ML filtering? 

Thank you

**Comment by aarzalluz** [comment]
Hi @cjy-23,

The `randomforest.RData` object is automatically stored in the working directory and, if the ML filter is run in the same folder, it will not be overwritten, but re-used. This is done even if any of the input parameters are changed, allowing to re-use an extant, already-trained classifier on new data if desired. Therefore, in principle, you would not need to set a seed. Is there any specific use case where this strategy is not working for you?

Best,

Ángeles

**Comment by cjy-23** [comment]
Hi Ángeles,

Thank you for your reply! I was just thinking if someone or I would ever need to re-run the SQANTI analysis and didn't have the `randomforest.RData` file then the results wouldn't be reproducible. But I think maybe I will just have to keep that file safe as you suggest. 

Thank you

**Comment by aarzalluz** [comment]
Hi @cjy-23,

Even though the issue is already closed, I just wanted to add something FYI. The SQANTI3 ML filter automatically sets seeds for all relevant steps of the model generation process (training, prediction and data partitioning), so there should be no reproducibility issues even in the case where the `randomforest.RData` is missing.

Best,

Ángeles
