### ISSUE TITLE
SQANTI3 ML filter error when input has no mono-exon transcripts

### ISSUE THREAD

**Issue by ajritter8** [ConesaLab/SQANTI3#184]
Here's how I ran sqanti3_filter.py:
```
python /Tools/SQANTI3-5.1.1/sqanti3_filter.py ML \
    --isoAnnotGFF3 ${inputDir}/sqanti3QC.gff3 \
    --isoforms ${inputDir}/sqanti3QC_corrected.fasta \
    --gtf ${inputDir}/sqanti3QC_corrected.gtf.cds.gff \
    --faa ${inputDir}/sqanti3QC_corrected.faa \
    -o sqanti3filterML \
    -d ${inputDir}/SQANTI3_Filter_ML \
    --threshold 0.6 \
    --max_class_size 5000 \
    --filter_mono_exonic \
    ${inputDir}/sqanti3QC_classification.txt
```

Here's the error I got:

> ------------------------------------------------
> 
> Applying Random Forest classifier to input dataset...
> 
> Random forest prediction finished successfully!
> 
> Random forest classification results:
> 
> Negative Positive
>    12690    16114
> Error in `$<-.data.frame`(`*tmp*`, "ML_classifier", value = NA) :
>   replacement has 1 row, data has 0
> Calls: $<- -> $<-.data.frame
> Execution halted
> 
> -------------------------------------------------

This caused the rest of the filter program to fail, including the filter report and generation of the filtered output files.
I suspect that this issue is because there are no single-exon isoforms in the dataset, so the following lines are causing the error:

```
# select mono-exons
  dme <- d1[setdiff(rownames(d1), rownames(isoform.predict)),]
  
  # set ML-related columns to NA
  dme$"NEG_MLprob"  <- dme$"POS_MLprob" <- dme$"ML_classifier"  <- NA
```

**Comment by aarzalluz** [comment]
Hi @ajritter8,

Thank you for your detailed description. I will run some tests in order to reproduce the error, but it seems reasonable to think that, as you pointed out, these lines of the code would throw an error with transcriptomes lacking mono-exonic isoforms. We were not expecting this to happen when we developed the script, but I can try to introduce some exceptions to handle it. 

Unfortunately, it will take some time for me to start working on this. In the meantime, maybe you can try a small hack: create a "fake" transcript in your `sqanti3QC_classification.txt` file with `exons == 1`, and set `--filter_mono_exonic` when running the ML filter script. That, I hope, should do the trick until this is fixed!

Hope that helps,

Ángeles

**Comment by ajritter8** [comment]
Hey Ángeles,

Thanks for the quick response.  I did use the —filter_mono_exonic argument,
but as I understand the code, that argument isn’t applied to the data until
later in the program.  In the meantime I commented out the lines generating
the “dme” dataframe (670, 673 and 676) and added the following lines to
SQANTI3_MLfilter.R:
d1 <- classified.isoforms
d1$"NEG_MLprob" <- d1$"POS_MLprob" <- d1$"ML_classifier" <- NA

This allowed the program to finish successfully and generate the expected
outputs.  I imagine a better way to do this would be to add an ifelse
statement that checks the dimensions of “dme” before proceeding.

One other question: the resulting filtered GTF file actually has more lines
than the GTF file I gave it to begin with.  It seems counterintuitive so
I’m wondering if that’s an expected outcome or not.

Best,

Alex

**Comment by aarzalluz** [comment]
Hi @ajritter8,

Yes, that argument only works if you actually have mono-exonic transcripts in your data, as it automatically labels all of them as artifacts, but they are not excluded from the output -no transcript is.

I will make a note of this and update the script with some appropriate error handling for mono-exons as soon as possible.

As for your second question, what you describe is not expected -SQ3 should actually be removing transcripts labelled as artifacts from your GTF, not the other way around. Could you open a separate issue providing some more details (input command, logs and so on)?

Best,

Ángeles

**Comment by aarzalluz** [comment]
Hi @ajritter8,

I know it has been a long time, but I did fix this bug -the ML filter now handles cases where there were no mono-exons in the input dataset.

I also realized that, in your response, you said that you included this line:
`d1$"NEG_MLprob" <- d1$"POS_MLprob" <- d1$"ML_classifier" <- NA`

...which is automatically setting all ML filter probabilities to NA. This will destroy the work done by the filter, since those computed probabilities are used to determine which isoforms are true and which ones are artifacts. Probability columns are set to NA for mono-exons because the random forest classifier cannot be applied to these transcripts. I'm not sure if this was something that you wanted to do in the first place, but I thought I'd let  you know.

The bug fix will be available in the next SQ3 release, which will be out soon.

Best,

Ángeles
