### ISSUE TITLE
MacOS Issue: utilities/gmst/probuild Unix Executable File yields error 'cannot execute binary file'

### ISSUE THREAD

**Issue by Sam-Koehler** [ConesaLab/SQANTI3#185]
Hello,

When attempting to run `sqanti3_qc.py` on my MacOS machine, I receive the following error message:

**Command**
```
## Define isoform file
isofile="${dir_isoforms}${i}.gtf"

## Classify and QC
python /path/to/SQANTI3-5.1/sqanti3_qc.py \
-d "out" \
-o "squanti-classify-qc" \
--isoAnnotLite \
"${isofile}" \
"${annotation}" \
"${genome}"
```

**Error**
```
**** Predicting ORF sequences...
/path/to/SQANTI3-5.1/utilities/gmst/probuild: /path/to/SQANTI3-5.1/utilities/gmst/probuild: cannot execute binary file
```

Attempting `chmod +x` on the `utilities/gmst/probuild` Unix Executable File has no affect.

Are the gmst tools only compatible on Linux systems?

Thank you for the help, your documentation has been very clear and helpful so far!

Best,
Sam

**Comment by aarzalluz** [comment]
Hi @Sam-Koehler,

Thank you for using SQANTI3 -glad to hear you find the documentation useful!

I am not sure whether there is a GMST version that is compatible with MacOS, but since the tools is currently not maintained, my recommendation would be to run SQANTI3 using the `--skipORF` argument to skip ORF prediction entirely. GMST usage within SQ3 is sometimes problematic, so I apologize for this.

Best,

Ángeles
