### ISSUE TITLE
Full-splice matches not properly classified  in QC output

### ISSUE THREAD

**Issue by avnanni** [ConesaLab/SQANTI3#194]
I am running SQANTI3 QC (v4.2) on two GTF files that contain all the same exons, but some have different transcript_id values. I wanted to match up those values and should get 100% FSM between the two. However, I am getting 770 transcripts incorrectly assigned to a different classification. A majority of these transcripts (747) are mono-exon, and the remaining have 2 exons. I checked each gene with one of these different classifications individually to make sure the GTF files are identical (they are for all cases). Please let me know if there is anything you think I may be missing.

Attached are my two GTF files (test_original.gtf was used as the "reference") and output classification file.
[test_classification.txt](https://github.com/ConesaLab/SQANTI3/files/11367762/test_classification.txt)
[test_new.gtf.gz](https://github.com/ConesaLab/SQANTI3/files/11367763/test_new.gtf.gz)
[test_original.gtf.gz](https://github.com/ConesaLab/SQANTI3/files/11367764/test_original.gtf.gz)

Thank you,

~Adalena

**Comment by FJPardoPalacios** [comment]
Hi @avnanni , 

In order to obtain a 100% FSM you have to set the `--min_ref_len` parameter to 0. [By default](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control#arguments-and-parameters-in-sqanti3-qc), SQ3 will ignore anything in the reference smaller than 200bp. That's why all your non-FSM transcripts are smaller than 200bp, because their matching reference was just ignored.

We set this as default to avoid spurious matches to really small genes that are all around the genome such as miRNA genes.

Bests,
Fran
