### ISSUE TITLE
how to generate pigeon reports from sqanti3_qc.py and qanti3_filter.py.

### ISSUE THREAD

**Issue by unique379r** [ConesaLab/SQANTI3#200]
hi
I have updated the SQANTI v5 to v5.1.1 as suppose to see the output report as pigeon but i cant find the tutorial in your page or the argument within the scripts above. Can you help me with this ?

Thanks

**Comment by aarzalluz** [comment]
Hi @unique379r,

I understand that pigeon runs SQANTI3 internally, however, since the SQANTI3 develpoment team is not the same as the pigeon team, we are unable to provide assistance with this. I suggest that you open an issue at the [pigeon repository](https://github.com/PacificBiosciences/pigeon).

Additionally, for future reference -and for us to be able to help out- it is generally recommended that issues contain a minimal amount of information, including how you are using SQANTI3, your input command, any error/warning messages you may have encountered, etc.

Best,

Ángeles
