### ISSUE TITLE
The _corrected.gtf.cds.gff is not generated when running SQANTI3 QC module

### ISSUE THREAD

**Issue by Rombar123** [ConesaLab/SQANTI3#201]
Dear developers, 

I ran SQANTI3 QC on Plasmodium falciparum LR-data, using the following command:

`python sqanti3_qc.py Plasmo_LR.gtf PlasmoDB-63_Pfalciparum3D7.gtf PlasmoDB-63_Pfalciparum3D7_Genome.fasta -o OUT --saturation --report both -n 10`

All the expected output files were generated except for the `_corrected.gtf.cds.gff` gtf file, that should contain CDS information based on GMST ORF predictions. I would appreciate your help in resolving this issue.

Thanks in advance.

**Comment by almart7** [comment]
Hello @Rombar123  sorry for the late reply! If that's okay with you, I could try to run SQANTI3 with your data to see what is the problem.

Kind regards!

**Comment by dudududu12138** [comment]
Hi， I met the same problem. So do you know the reason?

**Comment by dudududu12138** [comment]
Hi, I checked your source code, and I found the reason. It is due to the split function. When the `--chunk` parameter is set, the split function will be performed. But the `.cds.gtf.gff` files are not in the combined list. Maybe you forget. So while I don't set the `chunk` parameter, the `.cds.gtf.gff` file will be outputted.

**Comment by dudududu12138** [comment]
I ran sqanti_qc.py with and without `--chunk` parameter on the same data but I got different results. It is wired that the `_classification.txt` files are not identical. Especially some important column such as `associated_gene`, `RTS_stage`, `ORF_seq`, `ratio_TSS`. By the way, I sorted the two tables firstly by the transcript id column so the orders are the same.

**Comment by Fabian-RY** [comment]
Hi @dudududu12138 I've been reviewing this issue for the last week.
1. I've check the source code for the .cds.gtf.gff file and you're right - that file was missing. I have a fix for that and i'm testing the code to solve it so it's generated too
2. The differences between the classification files seems to be related to the parallelization itself: transcripts may be splitted between chunks and therefore some calculations are not done properly. For now, I haven't seen differences on the 4 important columns you mention, but I'll work on it to make sure the are no differences. I've opened a new issue with all the details I have about it, so any contribution you may have, please, post it there. 

I'll keep this issue open until i merge the fix for the .cds.gtf.gff file, to keep it akin to the original issue

**Comment by dudududu12138** [comment]
By the way ,I can got the `.cds.gtf.gff` file without set `--chunks`.  But the `gene_id` in `.cds.gtf.gff` file are different from the `gene_id` in `*_corrected.gtf`. 
This is the `gene_id` in `*_corrected.gtf:
```
GL000008.2      StringTie       transcript      83318   135086  .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001"
GL000008.2      StringTie       exon    83318   83545   .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
GL000008.2      StringTie       exon    83927   84014   .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
GL000008.2      StringTie       exon    85457   85477   .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
GL000008.2      StringTie       exon    85567   85625   .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
GL000008.2      StringTie       exon    129985  130583  .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
GL000008.2      StringTie       exon    133918  135086  .       +       .       transcript_id "tissues_00000005"; gene_id "XLOC_000001";
```
This is the `gene_id` in `*_corrected.cds.gtf.gff` file:
```
GL000008.2      PacBio  transcript      83318   135086  .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    83318   83545   .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    83927   84014   .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    85457   85477   .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    85567   85625   .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    129985  130583  .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
GL000008.2      PacBio  exon    133918  135086  .       +       .       transcript_id "tissues_00000005"; gene_id "novelGene_1";
```
