### ISSUE TITLE
ERROR with using SR_bam

### ISSUE THREAD

**Issue by hyeon9** [ConesaLab/SQANTI3#207]
First of all, Thank you for your shiny tool and maintenance.

When I used over 4 samples as SR_bam.fofn, I faced pandas merge error in utilities/short_reads.py.
To solve this problem I manually fixed name of column from "TSS_ratio" to bam_file, after that whole qc script run well.
I just want to suggest this minor change.

Thank you!!

**Comment by almart7** [comment]
Dear @hyeon9 thank you for telling us! Kind regards.

**Comment by hyeon9** [comment]
Hi all,

A few days ago, I reported this bug. 
In my case, I solved this problem by revising a column name variables in /SQANTI3-5.1.1/utilities/short_reads.py line 181-185 (I changed "merged["ratio_TSS"]" to "merged[bam_file]").
As I guess this error could be cased by pandas column naming method because they allows only three duplicated name in columns (e.g. Name_x, Name_y, Name).

Thank you!

**Comment by ESWRKJ** [comment]
> First of all, Thank you for your shiny tool and maintenance.
> 
> When I used over 4 samples as SR_bam.fofn, I faced pandas merge error in utilities/short_reads.py. To solve this problem I manually fixed name of column from "TSS_ratio" to bam_file, after that whole qc script run well. I just want to suggest this minor change.
> 
> Thank you!!

Hi @hyeon9 I would like to know how you modified it

**Comment by aarzalluz** [comment]
Hi all,

This bug has been fixed in the latest SQANTI3 release, **v5.2**. Please see the [installation instructions](https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation#1-downloading-sqanti3) for details. Note that this update will require users to create a fresh conda environment.

I'll be closing issue now, but please do let us know if the problem persists.

Ángeles
