### ISSUE TITLE
SQANTI3 not running with SR bam option

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#215]
To whom it may concern,

I tried to run SQANTI3 (newest version, 5.2.1) and am running into problems with the --SR_bam option. Specifically, it keeps giving me a strange error that "pandas.errors.MergeError: Passing 'suffixes' which cause duplicate columns {'ratio_TSS_x'} is not allowed." I've attached the full logfile with all relevant messages below. For the time being I'm running it without the --SR_bam option, but was wondering if there might be a fix available.

Thanks so much,
Ryan Englander

Jackson Labs, Anczukow Lab

[slurm-20316035.txt](https://github.com/ConesaLab/SQANTI3/files/12409882/slurm-20316035.txt)

**Comment by aarzalluz** [comment]
Hi @ryanpe13002 -some users seem to have encountered it as well (see #207). Thanks for reporting it, we will try to fix it as soon as possible.

Tagging @FJPardoPalacios so that he is aware of the bug.

Best,

Ángeles

**Comment by hyeon9** [comment]
Hi all,

A few days ago, I reported this bug. 
In my case, I solved this problem by revising a column name variables in /SQANTI3-5.1.1/utilities/short_reads.py line 181-185 (I changed "merged["ratio_TSS"]" to "merged[bam_file]").
As I guess this error could be cased by pandas column naming method because they allows only three duplicated name in columns (e.g. Name_x, Name_y, Name).

Kind regards,

**Comment by ryanpe13002** [comment]
Unfortunately, while this fix seemed to resolve some of the errors in the output file, this notably did not fully fix them... my run still quit while collecting the various split files (I ran with 20 threads) into the final output files. The final classification and junction files were partially written, but not completely. Notably, I am using the newest version (5.1.2)

**Comment by aarzalluz** [comment]
Hi all,

This bug has been fixed in the latest SQANTI3 release, v5.2. Please see the [installation instructions](https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation#1-downloading-sqanti3) for details. Note that this update will require users to create a fresh conda environment.

I'll be closing issue now, but please do let us know if the problem persists.

Ángeles
