### ISSUE TITLE
document install cdna_cupcake via bioconda

### ISSUE THREAD

**Issue by diekhans** [ConesaLab/SQANTI3#217]
cDNA_cupcake is in bioconda:

https://anaconda.org/bioconda/cdna_cupcake

**Comment by aarzalluz** [comment]
Update: isntallation of cdna_cupcake with bioconda does not work with current environment configuration.

For future reference, here is the log:

```
$ conda install -c bioconda cdna_cupcake
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - cdna_cupcake -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

```

**Comment by aarzalluz** [comment]
@Sparkle-27 I don't think it has been fixed yet -for now, it's probably best that you follow the installation instructions for cDNA_Cupcake at the wiki.

**Comment by aarzalluz** [comment]
A quick heads-up for current developers (tagging @almart7 even though I know you may not be the one in charge of fixing this):

Since the [IsoSeq toolkit](https://isoseq.how/) has taken over and cDNA_Cupcake is no longer supported by @Magdoll, it might be worth it to look into re-implementing the Cupcake-based functionalities of SQANTI3 using IsoSeq. I'm not sure to what extent it is feasible, but I'm certain that, in the long run, more deprecation issues and incompatibilities, such as the ones in #208, will arise.

**Comment by carolinamonzo** [comment]
This problem is now solved by using the Forked version of cDNA_Cupcake in the ConesaLab [repository](https://github.com/ConesaLab/cDNA_Cupcake). We have updated the installation in the SQANTI3 wiki and modified the setup.py to avoid the problems in cDNA_Cupcake's installation.
