### ISSUE TITLE
SQANTI3 QC throws GMST error during correctionPlusORF prediction

### ISSUE THREAD

**Issue by ESWRKJ** [ConesaLab/SQANTI3#224]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "/public/home/PacBio/ccs/FLNC/SQANTI3/sqanti3_qc.py", line 2537, in <module>
    main()
  File "/public/home/PacBio/ccs/FLNC/SQANTI3/sqanti3_qc.py", line 2520, in main
    run(args)
  File "/public/home/PacBio/ccs/FLNC/SQANTI3/sqanti3_qc.py", line 1870, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/public/home/jwtang/PacBio/FL_stickleback/ccs/FLNC/SQANTI3/sqanti3_qc.py", line 604, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/public/home/miniconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /public/home/jwtang/PacBio/FL_stickleback/ccs/FLNC/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /public/home/FL/FLNC/map/collapse/SQANTI3/GMST/GMST_tmp /public/home/FL/FLNC/map/collapse/SQANTI3/Gh_corrected.fasta' returned non-zero exit status 1.  
after iso-seq and TAMA, GTF file generated,but I encountered the above problem, I split half of the chromosome and it runs without any problems,but when running the complete chromosomes together, an error is always reported.

**Comment by aarzalluz** [comment]
Hi @ESWRKJ,

It is hard to debug without more information about the format of your input files, your input command, etc. What do you mind by "half the chromosomes"? What criteria did you use to split the data in order to stop the error? It would be useful to know in order to reproduce it.

According to the logs, it seems that there is a problem when running ORF prediction with GMST. Could you try running the program with `--skipORF` and see if the error persists?

Best,

Ángeles

PS: We urge users to provide informative titles for issues, as they make it easier for the rest of the community to find help.

**Comment by aarzalluz** [comment]
It seems like there is an offending sequence in one of the chromosomes that GMST cannot process. Since we are unable to debug GMST, you could try to find it and exclude it from your data, but if you do not need CDS prediction, I think it is best to proceed with the `--skipORF` results. 

Ángeles

**Comment by ESWRKJ** [comment]
thank you very much for your help
