### ISSUE TITLE
IsoAnnotLite protein features are not transferred

### ISSUE THREAD

**Issue by mintstella0419** [ConesaLab/SQANTI3#225]
Dear SQANTI3 team,

I have run IsoAnnotLite using my SQANTI output hoping to map the protein domains on my gff3 file, but none of the features with PosType=P are transferred. Is this a known issue or is there any reason why it might have happened?

Thanks!

**Comment by aarzalluz** [comment]
Hi @mintstella0419,

This could happen due to a couple of reasons:

- All the isoforms in your input transcriptome were predicted as non-coding (perhaps if you run SQANTI3 QC with the `--skipORF` flag).
- No overlaps, total or partial, were found between the CDS of the transcripts in the GFF3 file and the transcripts in your input GTF file.

However, I would need some more details in order to spot the problem: 

- Which organism and GFF3 file are you working with? 
- Which reference genome/transcriptome did you use to generate your input GTF file?
- What was your SQANTI3 input command? 
- Are the rest of the SQANTI3 output files generated correctly? 
- Are transcript-level features transferred, but not protein fetaures?

Best,

Ángeles

**Comment by carolinamonzo** [comment]
Closing since the user did not give any more information. We agree with the ideas of why this happened that Ángeles suggested.
