### ISSUE TITLE
error with --short_reads

### ISSUE THREAD

**Issue by ESWRKJ** [ConesaLab/SQANTI3#226]
Hi,
when I run  python /public/home/FLNC/SQANTI3/sqanti3_qc.py ../Gh_filter_remove.gtf /public/home/Ghirsutum_gene.gtf /public/home/Ghirsutum_genome.fasta --short_reads short_reads.fofn --saturation --cpus 40   Reported this error "EXITING: because of fatal INPUT file error: could not open read file: /public/home/Iowa/SR/TM_1/SRR1695173_1.fastq.gz       /public/home/SR/TM_1/SRR1695173_2.fastq.gz
SOLUTION: check that this file exists and has read permision"  but I input file all exist and have  permission. Why?

**Comment by aarzalluz** [comment]
@ESWRKJ -could you try supplying decompressed files (`.fastq` instead of `.fastq.gz`) and see if the error persists?

**Comment by ESWRKJ** [comment]
there is new error,
EXITING because of FATAL ERROR: could not open genome file /public/home/Iowa/SRR14415009/FL/FLNC/map/collapse/2+3/STAR_index//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

**Comment by aarzalluz** [comment]
The error is thrown by STAR, and it is caused by the paths of the files not being correctly defined in your input command. There is more info in [this thread](https://www.biostars.org/p/483645/). 

Please, verify that the file paths are correct relative to the directory in which you are running SQANTI3. Also, I recommend that you set the output directory using  `-d` argument to have more control over where the output files are created.
