### ISSUE TITLE
Alternative file for reference transcriptome annotation

### ISSUE THREAD

**Issue by Jung19911124** [ConesaLab/SQANTI3#233]
Hi,

I have Iso-seq data, short-read RNA-seq data and CAGE-seq data of the same biological sample of a non-model species.
I would like to create a transcriptome model using SQANTI3 (of course we have the chromosome-scale genome assembly of this species). 

Here, I have a question.
Currently, we do not have reference transcriptome annotation, which is mandatory for sqanti3_qc.py. 
Is it possible to substitute another file, for example, a gtf file obtained by genome alignment of _de novo_ assembled RNA-seq data.

Any suggestions would be appreciated.

Jung

**Comment by almart7** [comment]
Dear @Jung19911124 , SQANTI3 is a quality control of long-reads defined transcriptomes built with other transcriptome-building tool. We do not recommend using SQANTI3 on raw long reads. You can read more about SQANTI3 in our [wiki](https://github.com/ConesaLab/SQANTI3/wiki/Introduction-to-SQANTI3).

Kind regards!

**Comment by carolinamonzo** [comment]
Hi Jung, as @almart7 explained, SQANTI3 is a quality control tool. For creating transcriptome models, you should use other tools such as FLAIR, TALON, mandalorion, isoquant, bambu, stringtie etc. 
Once you have created your transcriptome models, as you suggested, since it's a non-model organism where there is no reference GTF, you can run SQANTI3 with your own GTF file generated by the de novo alignment of your RNA data. 

All the best!
