### ISSUE TITLE
Target ids in kallisto gene expression matrix

### ISSUE THREAD

**Issue by Ismail-Curie** [ConesaLab/SQANTI3#25]
Hello,
I would like to know how to get the target ids in the gene expression in this format PB.X.Y as it is shown in the example.
Thank you,
Ismail

**Comment by Magdoll** [comment]
Hi @Ismail-Curie ,
Looking at the other issue you filed, I advise running minimap2 aligning your input to hg38 --> followed by Cupcake [collapse](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse) which will get you the PB.X.Y ids.

-Liz

**Comment by Ismail-Curie** [comment]
Hi @Magdoll,
what I want is to have the PB.X.Y ids in the gene expression matrix of short read sequencing, so I can use it later in tappas. is it possible to use Cupcake collapse on paired read sequencing fastq files?
Thank you,
Ismail

**Comment by Magdoll** [comment]
Hi @Ismail-Curie ,do you mean can `collapse_isoforms_by_sam.py` work on short read data? Is the already assembled short read (into "full-length-ish" transcripts?) If so, it would be just fine since collapse script doesn't care what the input is.

If you are aligning paired end short reads (not assembled, paired) then collapse will not understand the paired end nature or the non-full-length nature of the data.
