### ISSUE TITLE
Error with random forest when running ML rescue

### ISSUE THREAD

**Issue by SamGallaher** [ConesaLab/SQANTI3#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [x] I have loaded the SQANTI3.env conda environment

### Problem description

I have been getting a fatal error when running the ML rescue step using the output from ML filter. The error is saying there are missing values in the randomforest.RData. Any help with this matter would be very much appreciated, thanks!

### Code sample
       rescue ml \ /SQANTI3/SQANTI3_output/PN0358/ML_Filter_output/PN0358_null_dmso/PN0358_null_dmso_MLresult_classification.txt \
       --refGenome /data/GRCh38.d1.vd1.fa \
    -o PN0358_null_dmso_full_ML \
    -d /SQANTI3/SQANTI3_output/PN0358/ML_Rescue_output_filter/PN0358_null_dmso \
    --isoforms /SQANTI3/SQANTI3_output/PN0358/QC_output/PN0358_null_dmso/PN0358_null_dmso_corrected.fasta \
    --refGTF /data/gencode.v45.annotation.gtf \
    --gtf /SQANTI3/SQANTI3_output/PN0358/ML_Filter_output/PN0358_null_dmso/PN0358_null_dmso.filtered.gtf \
    -r /SQANTI3/SQANTI3_output/PN0358/ML_Filter_output/PN0358_null_dmso/randomforest.RData \
    -j 0.7 \
    -k /SQANTI3/SQANTI3_output/PN0358/QC_output/PN0358_null_dmso/PN0358_null_dmso_classification.txt \
    --mode full

### Error

	RUN PRE-TRAINED SQ3 ML CLASSIFIER RUN ON REFERENCE TRANSCRIPTOME

	Reading SQANTI3 classification file...

	Performing ML filter data cleaning on classification...

	Checking column compatibility with pre-trained random forest classifier...

        Loading required package: magrittr
        Warning message:
        Failed to locate timezone database 

	Validating columns used in prediction...

	Column-level NA check:

	Column type check:

	Running random forest classifier on reference transcriptome...

        Error in predict.randomForest(modelFit, newdata, type = "prob") : 
        missing values in newdata

**Comment by aarzalluz** [comment]
Hi @SamGallaher,

This is normally caused because the pre-trained model is using QC attributes that are not present in the classification.txt file that you are supplying for the reference transcriptome. Please, verify that you have run SQANTI3 QC on your reference transcriptome using exactly the same supplementary data sources that you used to evaluate the long-read transcriptome.

If you used FL count values for long-read evaluation, which are by definition unavailable for the reference transcriptome, I can think of a couple of options to go around this error:
- You can manually alter the FL count column in the classification.txt file for your reference transcriptome, setting all values to 0 instead of NA.
- You can exclude FL counts from random forest classifier training via the -r argument when running the ML filter.

I hope that helps!

Ángeles

**Comment by carolinamonzo** [comment]
Closed since there's no response from the user, and we agree with Ángeles' suggestions.
