### ISSUE TITLE
SQANTI rules filtering with complex identifiers

### ISSUE THREAD

**Issue by hyeon9** [ConesaLab/SQANTI3#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

Hi SQANTI3 team,
Thank you for your shiny tool for long read data !

Recently, I've faced some error.
When I used nanopore data in SQANTI filtering step, I got below error message.

**Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
line 10 did not have 48 elements
Calls: read.table -> scan**

When I checked my classification.txt file, all line has 48 elements.
I think their isoform_id might be problematic because they don't have "." in their isoform_id. "AAACCCAAGACATACA_GGTTCCAACAGA#a7cf31cf-5340-4250-8212-ba013dc50e80_+-0".

If my guess is right, could you please add appropriate mode for nanopore data?

Thank you,
Hyeongu

### Code sample

conda activate ./miniconda3/envs/SQANTI3.env

code_dir="/Tool/SQANTI3-5.1.1/"
params=$1
json=$2
input="inputs/"
out="outputs/"
code_dir="SQANTI3-5.1.1/"

for i in Std_1st_SQANTI3 2hr-test1_1st_SQANTI3 2hr-test2_1st_SQANTI3
do
python ${code_dir}sqanti3_filter.py rules \
    -o ${params} \
    -d ${out}${i}/${params}_filtering \
    --gtf ${out}${i}/1st_SQANTI3_corrected.gtf \
    --isoforms ${out}${i}/1st_SQANTI3_corrected.fasta \
    -j ${json} \
    ${out}${i}/1st_SQANTI3_classification.txt
done

### Error

-------------------------------------------------

         Reading classification file

--------------------------------------------------
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 10 did not have 48 elements
Calls: read.table -> scan
Execution halted

**Comment by aarzalluz** [comment]
Hi @hyeon9,

A couple of things:

- Just reading your issue message, it is not possible to trace the error back to any specific module of the filter script. It would be useful to provide the traceback.
- I believe the issue title is not accurate. This is unlikely to be Nanopore-specific issue, since SQANTI3 is entirely compatible with ONT.
- The SQANTI3 filter is *agnostic to ID formatting*. We do not require dots (".") in them, but take the identifier as is. 

Having strange characters in your identifiers can always be problematic, regardless of the software tool you use. My suggestion would be to re-format your IDs to convert them to a simpler string, and see if the issue persists.

Ángeles

**Comment by hyeon9** [comment]
Hi Ángeles,

I've tested SQANTI3 filtering with simple ID, such as ONT.x.
This format worked well.
I believe an unusual ID result from BLAZE has caused this error to occur.

Thank you,
Hyeongu
