### ISSUE TITLE
Unique STAR run when running multiple chunks

### ISSUE THREAD

**Issue by carolinamonzo** [ConesaLab/SQANTI3#296]
### Discussed in https://github.com/ConesaLab/SQANTI3/discussions/293

<div type='discussions-op-text'>

<sup>Originally posted by **MartinezRuiz-Carlos** April 24, 2024</sup>
I find that the chunk parallelisation for the QC step with -n works very well, however, it becomes unusable when running the alignment with STAR. Giving multiple chunks will try and run STAR (index and alignment) as many times as chunks provided. This seems unnecessary and results in very large amounts of memory being requested. Would it be possible to have a single STAR run regardless of the number of chunks requested in the -n argument?
Many thanks!
</div>

**Comment by zhangkn3** [comment]
Hi Carolina,
I met the same problem with my data.
I am running the QC step on long-read sequencing data of a tumor sample. The raw fasta file is about 100GB.
If I run with -n, the script will hit the memory limitation (even if I called 500Gb for the job). But if I run without -n, the step has been running for 42 days. How do you think of the time, should it be running correctly now?

Looking forward to your kind response!

Best,
Kenan

**Comment by carolinamonzo** [comment]
Hi @zhangkn3, 42 days sound like a lot. Are your datasets very big?

I think the easiest way to bypass this problem (also for @MartinezRuiz-Carlos) is running STAR beforehand on your short reads, and then providing the bam (parameter --SR_bam) and SJ.out (parameter -c) files to SQANTI, instead of running STAR within SQANTI. This is explained in the [wiki](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control#providing-short-reads)

Best,
Carolina

**Comment by zhangkn3** [comment]
Hi Carolina,
Thanks for the kind response. I am running the script just on one sample. I will take your advice, and add the bam files to SQANTI.

And, here is the log file. It seems to be stopped because of the outage of the computer cluster and did not get the final result.

[slurm-30722809.log](https://github.com/ConesaLab/SQANTI3/files/15291635/slurm-30722809.log)

And, here is the script. Hope you can provide some suggestions. Best, Kenan.

echo "Starting sqanti3"
module load Anaconda3/5.0.1-gcb01
source activate /gpfs/fs1/home/kz116/miniforge3/envs/SQANTI3.env
export PYTHONPATH=$PYTHONPATH:/gpfs/fs1/home/kz116/sqanti3/cDNA_Cupcake/sequence/

sqanti3/SQANTI3-5.2/sqanti3_qc.py /gpfs/fs1/data/Archived_result/7_bam2gff/filtered_minimaped_GBM011.sort.bam.gff \
                                  /gpfs/fs1/data/hg38.knownGene.gtf \
                                  /gpfs/fs1/data/hg38.fa \
								  --skipORF \
								  --force_id_ignore \
								  --short_reads /gpfs/fs1/data/Archived_bash/10_sqanti3_AS/sr_locate.fofn \
								  -t 16 \
								  -o GBM011_test \
								  -d /gpfs/fs1/data/Archived_result/10_SQANTI3_AS_gfftest \
								  --report both
echo "sqanti3 test Completed"

**Comment by lkondratova** [comment]
@zhangkn3 now you should be able to multiprocess isoform classification without multiple STAR runs. Please, update SQANTI3 or sqanti3_qc.py file in your SQANTI3 repository. Please, let us know if you encounter any problems.

**Comment by zhangkn3** [comment]
Thanks! I will update the pipeline and come back to you after getting result from that. Best, Kenan
