### ISSUE TITLE
FL abundance file

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#3]
Good evening!
I have Multi Sample Demux FL Count, from whch I had 3 multiplexed samples. As I could understand SQANTI3 wouldn't accept multiple samples (so it wouldn't accept the 3 gff files in a single run). So I was planning to run sample1, then sample2, then sample3. but the Multi Sample Demux FL Count has the file count of all the 3 samples. should I separate the Multi Sample Demux FL Count file in 3, and run with its respective sample?

id,sample1,sample2,sample3
PB.1.1,3,10,
PB.1.2,0,11,
PB.1.3,4,4

**Comment by FJPardoPalacios** [comment]
I don't know if I got the question right. So you had one single transcriptome that was demultiplexed into 3?
SQANTI3 is a QC tool that will put together all the information that you gave to it in order to know how much you can "trust" an isoform. If one isoform was found in sample1 with 1 FL read, it is not "strongly supported" and you may consider to remove it from your final transcriptome. However, if that very same isoform is supported with a much higher number of FL reads in sample2 or sample3, and you don't take that into account, you may consider something as unreliable when it is just simply lowly expressed in that certain sample.

My suggestion would be to run SQANTI3 for the initial transcriptome with the multi sample demux FL count. The final classification file will include a "FL" column which will contain the sum up of FL reads across samples, but also the columns "FL_sample1", "FL_sample2" and "FL_sample3". It will make much easier any comparison you may want to do between samples.

**Comment by BeatrizdeToledo** [comment]
Thanks! It is much clearer now
