### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by 1398206876** [ConesaLab/SQANTI3#38]
Hi,
Thanks for very very useful tool.when I use sqanti3_qc.py , I got "AttributeError: 'NoneType' object has no attribute 'group'".But I don't konw what is wrong?
This is my command 
"python /data5/home/zhanglab/wanghaoyu/software/SQANTI3/sqanti3_qc.py /
--gtf ERR1597963_correctedReads_collapse.fasta.collapsed.gff /
IWGSC_v1.1_HC_20170706.split.gtf /
161010_Chinese_Spring_v1.0_pseudomolecules_parts.fasta --is_fusion" 
And the file "ERR1597963_correctedReads_collapse.fasta.collapsed.gff" is the output of collapse_isoforms_by_sam.py from cupcake.
Thank you !!!!!

**Comment by Magdoll** [comment]
Hi @1398206876 ,

Why did you run it with `--is_fusion`? That is reserved only for if you ran `fusion_finder.py`. 

Since you ran `collapse_isoforms_by_sam.py`, please try it without `--is_fusion`. If you still encounter error, please post th entire error message include which line of code in `sqanti3_qc.py` caused it.

-Liz

**Comment by Magdoll** [comment]
Closing unless OP reopens.
