### ISSUE TITLE
invalid gffGroup

### ISSUE THREAD

**Issue by mei-du** [ConesaLab/SQANTI3#51]
Hi team,
I ran into this error while running SQANTI3 on my FLAIR output gtf file. I'm thinking of contacting the FLAIR authors too but could you please clarify this?

Thank you!
<img width="1355" alt="Screen Shot 2021-04-08 at 14 52 02" src="https://user-images.githubusercontent.com/58542302/113980946-6ad22d80-988a-11eb-9ca9-41a2d34007a3.png">

**Comment by FJPardoPalacios** [comment]
Hi Mei,

It seems that there is something weird going on with your GTF. Can you send us a few lines of that FLAIR output GTF?

I know that after running FLAIR collapse you get also a FASTA file with the sequences of your transcripts. You can try to run SQANTI3 using directly the sequences.

Fran

**Comment by mei-du** [comment]
Hi Fran, I've just invited you to my repository. Thanks!

**Comment by FJPardoPalacios** [comment]
Well, it seems that all the transcripts in your GTF are mono-exon. That will probably cause several problems to SQANTI3, because it is designed for analyze transcriptomes with at least some splicing.

Moreover, as it is described in the error message you posted, some transcripts IDs are ambiguous. For example, transcript_id=m64087_200427 can be found in scaffold GL000213.1 and KI270734.1. That cannot occur.

Please, double check how you built your GTF or simply provide to SQANTI3 your reads

**Comment by mei-du** [comment]
Hi Fran, not entirely sure what happened (FLAIR was initially run by someone else) but I re-ran FLAIR and the gtf successfully worked with SQANTI3. Thanks for your help.
