### ISSUE TITLE
sqanti3_RulesFilter.py v1.6 flips the last column of the gtf which makes isoAnnot v2.6 not produce the exon rows

### ISSUE THREAD

**Issue by abrantesas** [ConesaLab/SQANTI3#57]
When I run  sqanti3_RulesFilter.py v1.6 and then isoAnnot v2.6
I get this message in the log for isoAnnot:

	TRANSCRIPT-LEVEL SUMMARY

		Â·A total of 0.00 % of transcripts in the GTF target annotation file (0 of 20066) were annotated because they matched a transcript ID in the GFF3 source annotation file (SQANTI FSM and ISM).

edit: ( I wasn't clear that the annotated file generated by isoAnnot is missing the exon rows after running the filter script and isoAnnot)

I ran isoAnnot on the unfiltered output and the exon rows are present. I grep a PBID on the filtered and unfiltered gtf, classification.txt, and junctions.txt and the only difference is that the last column of the gtf is flipped. 

transcript_id "PB.450.2"; gene_id "PB.450";
in the unfiltered gtf becomes 
gene_id "PB.450"; transcript_id "PB.450.2" 
after filtering.

Anthony

**Comment by abrantesas** [comment]
I reordered the filtered gtf with awk then ran isoAnnot and the exon rows were created.
Anthony

**Comment by FJPardoPalacios** [comment]
Hi Anthony, 

I think that your issue is not related with the order of the last column of the GTF. 

This very same thing happened to me the other day. The problem is that isoAnnotLite uses gene names from tappAS annotation file and it also expects gene names in the *associated_gene* column. It will not work if gene IDs are found. For example, gene_id=ENSG00000121390 and gene_name=PSPC1 point to the same gene, but IsoAnnotLite will work only if PSPC1 is specified. In order to avoid this problem, you should run SQANTI3 with the **--genename** option activated and then use sqanti3_RulesFilter.py and IsoAnnotLite_SQ3.py as you did. Hopefully that will allow you annotate your transcriptome. Please, let me know if other issue pop up.

We recently realized of this bug and it was fixed. Now, whenever it is specified the --isoAnnotLite on SQANTI3, it is also activated the **--genename** option. However, as you ran it step by step, you should be aware of activating **--genename** every time you run SQANTI3. We'll try to explain these situations better the next time.

Fran

**Comment by abrantesas** [comment]
But flipping the order of last column fixed the problem.

 I was wondering where I lost the gene names and how to incorporate them into tappAS. I will redo SQANTI with --genenname. Thanks for the tip!

**Comment by abrantesas** [comment]
I reran SQANTI3 with the new version 3.0 and --genename. I still had to use awk to flip the the order of the last column of the gtf that was produced by SQANTI in order for isoAnnot to work.

**Comment by Magdoll** [comment]
@abrantesas  remind me to look into this if I don't by end of next week. should be a quick fix.

**Comment by abrantesas** [comment]
OK will do.
