### ISSUE TITLE
Since previous was closed but not solved ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by michalkowalski94** [ConesaLab/SQANTI3#62]
Once again same thing, assertion error while running SQANTI3 on GTF's generated by StringTie.
```
File "/home/MCB/mkowalski/.conda/envs/SQANTI3.env/lib/python3.7/site-packages/cupcake-24.3.                                                                                                                                                                                         0-py3.7-linux-x86_64.egg/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-'
AssertionError
```

**Comment by FJPardoPalacios** [comment]
Hi,

I think it was explained in the closed issue #56 . I wouldn't say it is a SQANTI3 issue, but a StringTie one. 

SQANTI3 needs the strand of each transcript to evaluate it because:
- It is not the same to evaluate a 5' end or a 3' end.
- Canonical splice junctions would become non-canonical if we talk about the complementary strand.
- We could not assess if a transcript is matching the reference or it is a perfect anti-sense isoform if we don't know the strand.
- We cannot extract the sequence of a transcript and predict if it is a coding one. 
As you can imagine, the strand of an isoform is a pretty crucial information and **it must always be "+" or  "-".** 

My suggestion is to contact with StringTie people or simply remove those transcripts with a "." in the strand column (if they are not a high proportion of your transcriptome).

Best regards,
Fran
