### ISSUE TITLE
Short-read expression not working: converting ENST to pabcio IDs

### ISSUE THREAD

**Issue by mapostolides** [ConesaLab/SQANTI3#66]
Hi @Magdoll:
 
I am trying to integrate short-read Kallisto expression data as input to SQANTI3.

I am getting this message for all isoforms:

```
WARNING: isoform PB.4871.1 not found in expression matrix. Assigning TPM of 0.
```
This is resulting in expression values in the `iso_exp` field of the SQANTI3 output file `<>.transcriptome.sqanti3_classification.txt` being `0` for all isoforms. I think it is probably because Kallisto provides the expression matrix in the following format:
```
target_id       length  eff_length      est_counts      tpm
ENST00000634198.1       402     292.556 1       0.16513 
```
…and the transcript ID `ENST00000634198.1` cannot be mapped to any pacbio transcript ID such as `PB.4871.1 `. 

I tried to find some sort of reference file for converting PB.4871.1 pacbio IDs to ENST IDs, but couldn’t find anything on the web

How can I convert ENST IDs to pacbio IDs, or vice versa? Is there some feature of SQANTI or another tool which does this?

**Comment by FJPardoPalacios** [comment]
Hi @mapostolides ,

If you want to quantify your PacBio-defined transcriptome, you shouldn't use the ENSEMBL reference transcriptome with Kallisto but your new transcriptome (it will contain many novel isoforms and you want to measure their abundance too). So it won't be needed any mapping between ENST IDs and PB IDs for quantification. SQANTI3 will link your new isoforms with already annotated genes/transcripts using our Structural Categories (FSM, ISM, NIC, NNC...).

I guess that you downloaded SQANTI3 before the latest release (v4.0). If you have Illumina pair-end data, now SQANTI3 will do all the job for you, including Kallisto's quantification and the SJ detection with STAR. You just have to create a File Of File Names (.FOFN) with the paths to your short-read FASTQ files and use it through the `--short_reads` option. FOFN format should be a simple text file with one line per replicate and, in each line, 2 paths separated by one space.
```
/path/to/replicate1_read1.fastq /path/to/replicate1_read2.fastq
/path/to/replicate2_read1.fastq /path/to/replicate2_read2.fastq
``` 

**Remember:** These are totally new functionalities, if you want to take advantage of them you must download the latest SQANTI3 version (v4.0) and create again the conda environment using the updated YML file. And of course, allocate more computing resources for running it, since it will need them to do the mapping and the quantification.

I'm sorry for not having documented all these changes yet, I'm working on that. There is already some information in the Wiki of the new functionalities, but if you have any question just let me know!

Bests,
Fran

**Comment by mapostolides** [comment]
@FJPardoPalacios  Thank you for your response! Those sound like some awesome new features

Best,
Michael
