### ISSUE TITLE
Can I change the working directory of sqanti_qc?

### ISSUE THREAD

**Issue by ttbond** [ConesaLab/SQANTI3#70]
Hi~
I am using sqanti_qc and snakemake to process multiple iso-seq samples. But I found the the working directory cannot be changed (just under the directory where I run the script) which means I cannot parallel several process by snakemake.
So, could you give a parameter to set the workiing directory ? Or, If it exists, could you help to tell me how to set it ?
Thanks.

**Comment by ttbond** [comment]
Hi~
Thanks for your kind reply. But -d argument dosen't work.
```python
{python} {sqanti3} -t {threads} -n 7 -d {workD} -o {outP} --report pdf --gtf {isoformsGtf} {annotation} {genome}
```
The "splits" directory is not in {workD}, but still locates at where I run snakemake. I must run SQANTI3 one by one.
The version I used is 
```python
R scripting front-end version 4.1.0 (2021-05-18)
SQANTI3 3.3
```
And I checked the python scripts sqanti_qc.py. There is no code that can set "splits" directory.
May be this is a bug for parallel using of SQANTI3.

**Comment by FJPardoPalacios** [comment]
You are right. It's a bug that occurs when `-n` is activated.

I'll mark this as a bug. As soon as I fix it I'll write back and let you know.

Thank you!
Fran

**Comment by FJPardoPalacios** [comment]
Hi @ttbond ,

It should be fixed now. Please, update your SQANTI3 scripts and try to run it through snakemake using `-n` as you were using it before. 

I would like to let you know that with the latest version (currently v4.1) we moved towards making GTF the default input format for the isoforms instead of FASTA. Mapping might introduce some unexpected results sometimes and we recommend to use your own GTF. In the case that you only have the sequences of the transcripts, then mapping is inevitable and the `--fasta` option must be activated. This means that, regarding the code you posted previously, you should remove the `--gtf` argument to run SQANTI3 now.

Please, let me know if the bug was fixed. Thanks!

Fran
