### ISSUE TITLE
classification error 

### ISSUE THREAD

**Issue by vetsuisse-unibe** [ConesaLab/SQANTI3#73]
Hi all 
I ran squanti3 according to the tutorials (sqanti3_qc.py and sqanti3_RulesFilter.py)  I have a doubt in the classification.txt. A isoform with a mRNA associated transcript id has been classified as non-coding by sqanti3. I have some examples below. 

PB.403.1	chr1	+	458	4	full-splice_match	RPS27L	XM_003363667.4	572	4	111	3	111	-3	multi-exon	FALSE	canonical	NA	NA	NA	NA	NA	NA	NA	FALSE	NA	NA	NA	C	non_coding	NA	NA	NA	NA	NA	NA	NA	15.0	AAATTTTCCCTTTTTTTTTT	NA	NA	NA	NA	NA	NA	NA

PB.453.1	chr1	-	2490	3	full-splice_match	SERF2	XM_005603072.3	608	3	93	-1975	93	1975	multi-exon	FALSE	canonical	NA	NA	NA	NA	NA	NA	NA	FALSE	NA	NA	NA	C	non_coding	NA	NA	NA	NA	NA	NA	NA	25.0	AGAATCTGAGCATTCTGGGT	NA	NA	NA	NA	NA	NA	NA

PB.577.1	chr1	-	2304	3	full-splice_match	RPS29	XM_001494060.5	489	3	33	-1848	33	1848	multi-exon	FALSE	canonical	NA	NA	NA	NA	NA	NA	NA	FALSE	NA	NA	NA	A	non_coding	NA	NA	NA	NA	NA	NA	NA	35.0	AAAAGAATGAGTTGTGTTTT	NA	NA	NA	NA	NA	NA	NA

Can anybody explain me why this so ? Thank you very much 

regards
Vidhya

**Comment by FJPardoPalacios** [comment]
Hi,

SQANTI3 runs GeneMark S-T to predict if an isoform is coding or not, regardless if it was associated to a known transcript or not.

In your case, it seems that those isoforms didn't match the criteria that GeneMark established to say that they are coding (this criteria might not be the same that the one used by RefSeq). In fact, all your isoforms were predicted by automated computational analysis from the genomic sequence. Moreover, even though they are FSM, the last 2 isoforms are way larger than their associated transcript in the reference: they are 2.4 and 2.3 kb long meanwhile in the reference they have just 608 and 489 bp, respectively. 

SQANTI3 does not assume (and we shouldn't do either) that if an isoform have the same SJ chain than one transcript in the reference (what we call a FSM), they are the same. They might not be because of big differences at the transcription starting and ending sites.

Bests,
Fran
