### ISSUE TITLE
ISM and FSM annotated to same transcripts

### ISSUE THREAD

**Issue by SziKayLeung** [ConesaLab/SQANTI3#77]
Hi Liz and Fran, 

Thank you for continuing to maintain SQANTI3! 

I’ve successfully been using SQANTI for annotations, but have noticed a lot of cases where I have several full-splice match and incomplete-splice match transcripts annotated to the same associated_transcript (I’ve attached an example of SNCA after SQANTI filtering with default parameters). 

Using one of Tama’s scripts (tama_remove_fragment_models.py - https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Transcript-Filtering), only the longest FSM is retained (in this example PB.6948.1, highlighted green), suggesting that all the other FSM and ISM transcripts are shorter fragments (Indeed blasting the longest FSM with one of the shorter transcript reveal 100% alignment but only 28% coverage).  However, the longest FSM annotated the transcript also has the lowest read counts (possibly due to RNA degradation?), which would have downstream implications.

I was therefore thinking of collapsing all the FL counts of FSM transcripts and ISM transcripts annotated to the same associated transcript, while keeping the longest FSM transcript as annotation. However, would it be correct to assume that ISM transcripts and the shorter FSM transcripts are partial products of the same transcript as the longest FSM? 

For general purposes, what would be your advice on handling ISM and multiple FSM transcripts downstream? Should they be considered separate unique isoforms (so in the example attached, 7 unique isoforms) or the same isoform, and would you advise to include their counts for quantification? 

Any thoughts on this would be greatly appreciated! 

Thank you, 
Szi Kay

![SNCA](https://user-images.githubusercontent.com/33493350/126907466-f633c01a-0d39-4411-93d0-ed958bddb484.png)
![blast_summary](https://user-images.githubusercontent.com/33493350/126907468-3aa2b855-75d9-4a12-97bf-e7e343af4195.png)
![blast](https://user-images.githubusercontent.com/33493350/126907469-73b37354-0116-44c3-a7bb-7a9c5f74cfae.png)

**Comment by Magdoll** [comment]
Hi @SziKayLeung ,

I think the choice of "what to do with ISMs" is a tough q. Because as you say there are a few options:
 - (1) assume they must be a partial product of the longer FSM => keep only longer FSM, merge counts
 - (2) assume they are potential alternative transcripts => keep ISM 
 - (3) simply ignore them => remove from the transcriptome, ignore the counts
 - (4) something more complicated, if it maps to multiple FSMs


The issue here is the shorter the ISM transcript is, the more likely it could have come from multiple FSMs. Simply seeing "a longer FSM" that the ISM is partial to does not guarantee it is the *only* FSM that is can be a legitimate partial product of. 

I don't have a great answer. Historically I've done either approach (1) or approach (3). If it's targeted sequencing where I expect a lot of depth, I would use (3), because the ISMs can really come from a lot of FSMs and I care about isoform counts deeply. Otherwise I sometimes go with (1).

Hope that makes sense.

-Liz

**Comment by SziKayLeung** [comment]
Hi Liz, 

Thank you - it makes sense and I guess the approach is dependent on the experiment and the aims of downstream analysis. My only issue with approach (3) with targeted sequencing is that I'm seeing quite a lot of potential degradation and truncation so actually my isoform counts for the FSM is relatively low. 

But thanks for your answer!
