### ISSUE TITLE
filtered or corrected as the final result?

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#85]
Hi,
Thanks for the recent update. I finally can run it~~~
However, I found in the output, there are classification.filtered_lite_SQANTI3_report.pdf/html/gtf, and corrected.pdf/html/gtf. Should I use the filtered or the corrected output as my finial result? The corrected version files have more isoforms...thanks
Best
Xiaona

**Comment by FJPardoPalacios** [comment]
Hi,

`*corrected.pdf/html/gtf*` are the results of `sqanti3_qc.py` script and they contain information about your transcriptome. We called those files "corrected" because all the sequences and analysis are done using the genome-corrected version of your transcriptome. This means that if any of your initial reads had a SNP, it won't be possible to find it in the `*corrected.fasta` file and it will not have any effect when predicting CDS, for example.

I guess that if you have those `*filtered_lite_SQANTI3*` files it's because you ran the `sqanti3_RulesFilter.py` script. Based on a set of [rules](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-rules-filter), you filtered out all those isoforms that didn't fulfill them and you obtained a filtered version of your transcriptome. Then, to have an idea of what do you have in your filtered transcriptome, `sqanti3_RulesFilter.py` generates again a report, but only taking into account those isoforms that where considered "good enough".

I can't tell you what to use for your final result, since I don't know what it is your expected final result. However, if you have a filtered version with better quality attributes because you have removed some possible artifacts that might compromise any downstream analysis, I would recommend you to use the filtered version.

Fran

**Comment by xiaonalu** [comment]
Thank you Fran,
My goal is to discover new isoforms. I look through the filter rules, while confusing about the [-a INTRAPRIMING] and [-r] 
"-a: the fraction of genomic 'A's above which the isoform will be filtered. The default is -a 0.6." Does it mean if the transcript have the length with the amount of adenylate more than 60% of entire length, it will be removed?
"-r is another option for looking at genomic 'A's that looks at the immediate run-A length. The default is -r 6." Also is this telling those transcripts which have equal or more than continuous 6 adenylate will be filtered out? 
Thank you so much
Xiaona
