### ISSUE TITLE
Transcriptome builds using Long reads, short reads and SQANTI

### ISSUE THREAD

**Issue by sanyalab** [ConesaLab/SQANTI3#98]
Hi,

This is not an issue. But I am looking for a protocol to build a transcriptome assembly using long and short reads and SQANTI for quality assessment. If there are some critical papers or the method that you use in the lab, which gives a a high-quality full-length transcript, maybe I can start there. I work with non-human species.

Best Regards
Abhijit

**Comment by FJPardoPalacios** [comment]
Hi Abhijit!

There are a few tools for getting your new transcriptome using Long Reads (LR) and Short Reads (SR). I have always used [IsoSeq3](https://github.com/PacificBiosciences/IsoSeq) since it is the default PacBio pipeline and we have been working with it for a long time. It doesn't use SR to build transcript models directly, but you can combine LR and SR with SQANTI3 and filter out those isoforms that are not "good enough" for you.

However, there are more tools that you might want to look at:
- [TALON](https://github.com/mortazavilab/TALON): This is the pipeline defined by ENCODE to process long-read RNA-Seq data.
- [FLAIR](https://github.com/BrooksLabUCSC/flair): This pipeline uses both LR and SR. I've used it a couple of times and it is easy to run.
- [TAMA](https://github.com/GenomeRIK/tama): This is more like a tool-box for doing so many thing with your transcriptome. I would strongly recommend you **TAMA collapse** to have a better control of the redundancy that you will found in your transcriptome.

Of course, you can use SQANTI3 with your SR after all of them and check how it went.

I wish I could tell you that X method is the best performing in your situation (non-human organism, short and long reads available...), but we are currently working on that through the [LRGASP Consortium](https://www.gencodegenes.org/pages/LRGASP/). Probably in the next months we will have more information to share about which pipeline is more suitable for you, so stay tuned if you are interested!

Bests,
Fran

**Comment by sanyalab** [comment]
Hello Fran,

Thank you for the detailed reply. This helps plenty. I have always used PASA and EVM for doing the transcriptome builds, but I find that many times the tool is very conservative. Therefore, doing some research. Thank you for pointing out the LRGASP consortium. I'll stay tuned. Last question.

If I do not have access to CAGE-Seq or 3P RNA-Seq data, is there a protocol that you are aware of, to get the approximate position of TSS and TTS using LR and SR reads? 

Thanks
Abhijit
